export const motionStyleProps = {
  x: true,
  y: true,
  z: true,
  translateX: true,
  translateY: true,
  translateZ: true,
  rotate: true,
  rotateX: true,
  rotateY: true,
  rotateZ: true,
  scale: true,
  scaleX: true,
  scaleY: true,
  scaleZ: true,
  skew: true,
  skewX: true,
  skewY: true,
  originX: true,
  originY: true,
  originZ: true,
  perspective: true,
}

// todo we can probably get rid of this by just not having isDOMElement? or some new flag
export const motionExtraProps = {
  animate: true,
  custom: true,
  drag: true,
  dragConstraints: true,
  dragElastic: true,
  dragMomentum: true,
  dragPropagation: true,
  dragTransition: true,
  exit: true,
  initial: true,
  layoutTransition: true,
  onAnimationComplete: true,
  onAnimationEnd: true,
  onAnimationStart: true,
  onDirectionLock: true,
  onDrag: true,
  onDragEnd: true,
  onDragStart: true,
  onHoverEnd: true,
  onHoverStart: true,
  onPan: true,
  onPanEnd: true,
  onPanStart: true,
  onTap: true,
  onTapCancel: true,
  onTapStart: true,
  onUpdate: true,
  positionTransition: true,
  transformTemplate: true,
  transition: true,
  variants: true,
  whileHover: true,
  whileTap: true,
  useInvertedScale: true,
}
