import { ThemeObject, ViewPropsStrict } from '@mcro/gloss';
import React from 'react';
export declare type ItemRenderText = ((text: string) => JSX.Element);
export declare type HandleSelection = ((index: number, eventType: 'click' | 'key', element?: HTMLElement) => any);
export declare type ListItemHide = {
    hideTitle?: boolean;
    hideIcon?: boolean;
    hideSubtitle?: boolean;
    hideBody?: boolean;
    hideItemDate?: boolean;
    hideDate?: boolean;
    hideMeta?: boolean;
};
export declare type ListItemDisplayProps = {
    oneLine?: boolean;
    condensed?: boolean;
};
export declare type ListItemProps = ViewPropsStrict & ListItemHide & ListItemDisplayProps & {
    subId?: string | number;
    location?: React.ReactNode;
    preview?: React.ReactNode;
    title?: React.ReactNode;
    subTextOpacity?: number;
    slim?: boolean;
    above?: React.ReactNode;
    activeStyle?: Object;
    before?: React.ReactNode;
    chromeless?: boolean;
    theme?: Partial<ThemeObject>;
    listItem?: boolean;
    subtitle?: React.ReactNode;
    date?: Date;
    icon?: any;
    index?: number;
    isExpanded?: boolean;
    style?: any;
    afterTitle?: React.ReactNode;
    after?: React.ReactNode;
    titleProps?: Object;
    iconBefore?: boolean;
    iconProps?: Object;
    separatorProps?: Object;
    className?: string;
    inGrid?: boolean;
    pane?: string;
    subPane?: string;
    renderText?: ItemRenderText;
    children?: React.ReactNode;
    onClick?: Function;
    disableSelect?: boolean;
    onSelect?: HandleSelection;
    onOpen?: HandleSelection;
    borderRadius?: number;
    nextUpStyle?: Object;
    isSelected?: boolean | ((index: number) => boolean);
    cardProps?: Object;
    disableShadow?: boolean;
    padding?: number | number[];
    titleFlex?: number;
    subtitleProps?: Object;
    getIndex?: ((id: number) => number);
    subtitleSpaceBetween?: React.ReactNode;
    searchTerm?: string;
    onClickLocation?: (index: number, e?: Event) => any;
    separator?: React.ReactNode;
    group?: string;
};
export declare const ListItem: React.NamedExoticComponent<ListItemProps>;
//# sourceMappingURL=ListItem.d.ts.map