version: '3'
services:
  couchdb:
    image: klaemo/couchdb:latest
    restart: always
    volumes:
       - ./app_data/couchdb:/usr/local/var/lib/couchdb
       - ./apps/couch/config:/usr/local/etc/couchdb
    restart: always
    expose:
      - 5984
    ports:
      - 5984:5984
  api:
    restart: always
    build:
      context: .
      dockerfile: infra/images/api.dockerfile
    volumes:
      - ./apps/api:/repo/apps/api
      - ./apps/web:/repo/apps/web
    ports:
      - 3000:3000
    links:
      - couchdb
    depends_on:
      - couchdb
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PROTOCOL=${DB_PROTOCOL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  public:
    restart: always
    build:
      context: .
      dockerfile: ./apps/public/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./apps/web:/repo/apps/web
    extra_hosts:
      - 'starter-host:$HOST_IP'
