version: '3'
services:

  # postgres
  postgres:
    image: "postgres:11.2"
    container_name: "orbit-postgres"
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
