version: "2"
services:
  # starter-redis:
  #   image: redis
  #   ports:
  #     - 6379
  #   volumes:
  #     - /data
  starter-couchdb:
    image: klaemo/couchdb:latest
    restart: always
    expose:
      - 5984
    ports:
      - 5984:5984
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  starter-api:
    image: index.docker.io/motion/starter-api:latest
    ports:
      - 80:3000
    links:
      - starter-couchdb
    depends_on:
      #  - starter-redis
       - starter-couchdb
    environment:
      - PORT=3000
      - DB_HOST=starter-couchdb
      - DB_PORT=5984
      - DB_PROTOCOL=http://
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
