version: '3'
services:
  # postgres
  postgres:
    image: 'postgres:11.2'
    container_name: 'orbit-postgres'
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
    ports:
      - '5942:5942'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'
