version: "2"
services:
  my-rethink:
    container_name: my-rethink
    hostname: my-rethink
    image: rethinkdb:2.3
    restart: always
    ports:
      - 8081:8080
      - 28010:28015
    volumes:
      - ./app_data/:/data:rw
  my-horizon:
    container_name: my-horizon
    hostname: my-horizon
    image: mhart/alpine-node:6
    command: node /app/apps/horizon/start
    restart: always
    expose:
      - 443
    volumes:
      - ./apps/horizon:/app/apps/horizon:ro
      - ./packages:/app/packages:ro
    links:
      - my-rethink
  # see: https://github.com/sameersbn/docker-postgresql
  # postgres:
  #   restart: always
  #   image: sameersbn/postgresql:9.6-2
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - DEBUG=false
  #     - DB_USER=
  #     - DB_PASS=
  #     - DB_NAME=
  #     - DB_TEMPLATE=
  #     - DB_EXTENSION=
  #     - REPLICATION_MODE=
  #     - REPLICATION_USER=
  #     - REPLICATION_PASS=
  #     - REPLICATION_SSLMODE=
  #   volumes:
  #     - /srv/docker/postgresql:/var/lib/postgresql
