version: '2'
services:
  pad-redis:
    image: redis
    ports:
     - 6379
    volumes:
     - ./app_data/redis-data:/data
  pad-couch:
    build:
      context: .
      dockerfile: infra/images/couch.dockerfile
      args:
        ENV: "dev"
    restart: always
    volumes:
       - ./app_data/couchdb:/opt/couchdb/data
       - ./apps/couch/config:/opts/couchdb/etc
    restart: always
    links:
      - pad-redis
    depends_on:
      - pad-redis
    expose:
      - 5984
    ports:
      - 5984:5984
  pad-api:
    restart: always
    build:
      context: .
      dockerfile: infra/images/api.dockerfile
      args:
        ENV: "dev"
    volumes:
      - ./apps/api:/repo/apps/api
      - ./apps/models:/repo/apps/models
      - ./apps/couch:/repo/apps/couch
      - ./node_modules:/repo/node_modules
      - ./packages:/repo/packages
    ports:
      - 3000:3000
      - 5858:5858
    expose:
      - 5858
    links:
      - pad-couch
    depends_on:
      - pad-couch
      - pad-redis
    environment:
      - PORT=3000
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_PROTOCOL=${DB_PROTOCOL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PUBLIC_URL=${DB_PUBLIC_URL}
  pad-web:
    restart: always
    build:
      context: .
      dockerfile: infra/images/web.dockerfile
      args:
        ENV: "dev"
    ports:
      - 80:80
    links:
      - pad-api
    volumes:
      - ./apps/web:/apps/web
      - ./apps/web/nginx:/apps/web/nginx
    extra_hosts:
      - 'starter-host:$HOST_IP'
