version: "2"
services:
  # starter-redis:
  #   hostname: starter-redis
  #   image: redis
  #   ports:
  #    - 6379
  #   volumes:
  #    - ./app_data/redis-data:/data
  starter-couchdb:
    hostname: starter-couchdb
    image: klaemo/couchdb:latest
    restart: always
    ports:
      - 5984:5984
    environment:
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
  starter-api:
    hostname: starter-api
    build: ./apps/api
    ports:
     - 3000:3000
     - 5858:5858
    depends_on:
      # - starter-redis
      - starter-couchdb
    environment:
     - PORT=3000
     - DB_HOST=${DB_HOST}
     - DB_PORT=${DB_PORT}
     - DB_PROTOCOL=${DB_PROTOCOL}
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
    #  - NODE_ENV=${NODE_ENV}
    #  - FROM_EMAIL=${FROM_EMAIL}
    #  - SENDGRID_USERNAME=${SENDGRID_USERNAME}
    #  - SENDGRID_PASSWORD=${SENDGRID_PASSWORD}
    #  - FACEBOOK_CLIENTID=${FACEBOOK_CLIENTID}
    #  - FACEBOOK_CLIENTSECRET=${FACEBOOK_CLIENTSECRET}
    #  - GOOGLE_CLIENTID=${GOOGLE_CLIENTID}
    #  - GOOGLE_CLIENTSECRET=${GOOGLE_CLIENTSECRET}
    #  - GITHUB_CLIENTID=${GITHUB_CLIENTID}
    #  - GITHUB_CLIENTSECRET=${GITHUB_CLIENTSECRET}
    #  - WINDOWSLIVE_CLIENTID=${WINDOWSLIVE_CLIENTID}
    #  - WINDOWSLIVE_CLIENTSECRET=${WINDOWSLIVE_CLIENTSECRET}
    #  - LINKEDIN_CLIENTID=${LINKEDIN_CLIENTID}
    #  - LINKEDIN_CLIENTSECRET=${LINKEDIN_CLIENTSECRET}
