version: '2'
services:
  pad-couch:
    image: klaemo/couchdb:latest
    restart: always
    volumes:
       - ./app_data/couchdb:/usr/local/var/lib/couchdb
       - ./apps/couch/config:/usr/local/etc/couchdb
    restart: always
    expose:
      - 5984
    ports:
      - 5984:5984
  pad-api:
    restart: always
    build:
      context: .
      dockerfile: infra/images/api.dockerfile
      args:
        ENV: "dev"
    volumes:
      - ./apps/api:/repo/apps/api
      - ./apps/web:/repo/apps/web
    ports:
      - 3000:3000
    links:
      - pad-couch
    depends_on:
      - pad-couch
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PROTOCOL=${DB_PROTOCOL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  pad-web:
    restart: always
    build:
      context: .
      dockerfile: infra/images/web.dockerfile
      args:
        ENV: "dev"
    ports:
      - 80:80
    links:
      - pad-api
    volumes:
      - ./apps/web:/apps/web
    extra_hosts:
      - 'starter-host:$HOST_IP'
