version: "2"
services:
  starter-redis:
    env_file: .env
    image: redis
    ports:
      - 6379
    volumes:
      - /data
  starter-couchdb:
    env_file: .env
    image: klaemo/couchdb:latest
    volumes:
       - /usr/local/var/lib/couchdb
    restart: always
    expose:
      - 5984
    ports:
      - 5984:5984
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  starter-api:
    env_file: .env
    build: ./apps/api
    ports:
      - 80:3000
    links:
      - starter-couchdb
    depends_on:
       - starter-redis
       - starter-couchdb
    environment:
      - PORT=3000
      - DB_HOST=starter-couchdb
      - DB_PORT=5984
      - DB_PROTOCOL=http://
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    #  - NODE_ENV=${NODE_ENV}
    #  - FROM_EMAIL=${FROM_EMAIL}
    #  - SENDGRID_USERNAME=${SENDGRID_USERNAME}
    #  - SENDGRID_PASSWORD=${SENDGRID_PASSWORD}
    #  - FACEBOOK_CLIENTID=${FACEBOOK_CLIENTID}
    #  - FACEBOOK_CLIENTSECRET=${FACEBOOK_CLIENTSECRET}
    #  - GOOGLE_CLIENTID=${GOOGLE_CLIENTID}
    #  - GOOGLE_CLIENTSECRET=${GOOGLE_CLIENTSECRET}
    #  - GITHUB_CLIENTID=${GITHUB_CLIENTID}
    #  - GITHUB_CLIENTSECRET=${GITHUB_CLIENTSECRET}
    #  - WINDOWSLIVE_CLIENTID=${WINDOWSLIVE_CLIENTID}
    #  - WINDOWSLIVE_CLIENTSECRET=${WINDOWSLIVE_CLIENTSECRET}
    #  - LINKEDIN_CLIENTID=${LINKEDIN_CLIENTID}
    #  - LINKEDIN_CLIENTSECRET=${LINKEDIN_CLIENTSECRET}
