version: "3"
services:
  couch:
    container_name: couch
    hostname: couch
    image: couchdb
    restart: always
    ports:
      - 5984:5984
    volumes:
      - ./apps/couch:/usr/local/etc/couchdb/local.d:rw
