version: "2"
services:
  starter-couchdb:
    image: klaemo/couchdb:latest
    restart: always
    volumes:
       - ./app_data/couchdb:/usr/local/var/lib/couchdb
       - ./apps/couch/config:/usr/local/etc/couchdb/local.d
    restart: always
    expose:
      - 5984
    ports:
      - 5984:5984
  starter-api:
    restart: always
    build:
      context: .
      dockerfile: infra/images/api.dockerfile
    volumes:
      - ./apps/api:/repo/apps/api
      - ./apps/web:/repo/apps/web
    ports:
      - 3000:3000
    links:
      - starter-couchdb
    depends_on:
       - starter-couchdb
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PROTOCOL=${DB_PROTOCOL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  starter-web:
    restart: always
    build:
        context: .
        dockerfile: infra/images/web.dockerfile
    image: nginx:stable-alpine
    links:
       - starter-api
       - starter-couchdb
    ports:
      - 80:80
    volumes:
      - ./apps/web:/app:ro
      - ./apps/web/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "starter-host:$HOST_IP"
