export const apps = [
  {
    icon: require('../../public/logos/jira.svg'),
    title: 'Jira',
    description: 'Data App: Read and write to Jira with a fully typed API.',
    downloads: '12,140',
    hearts: '52',
  },
  {
    icon: require('../../public/logos/drive.svg'),
    title: 'Drive',
    description: 'Data App: Read and write to Drive with a fully typed API.',
    downloads: '4,821',
    hearts: '23',
  },
  {
    icon: require('../../public/logos/slack.svg'),
    title: 'Slack',
    description: 'Data App: Read and write to Slack with a fully typed API.',
    downloads: '7,123',
    hearts: '47',
  },
  {
    icon: require('../../public/logos/github-octocat.svg'),
    title: 'Github',
    description: 'Data App: Read and write to Github with a fully typed API.',
    downloads: '4,489',
    hearts: '154',
  },
  {
    icon: require('../../public/logos/gmail.svg'),
    title: 'Gmail',
    description: 'Data App: Read and write to Gmail with a fully typed API.',
    downloads: '3,123',
    hearts: '20',
  },
  {
    icon: require('../../public/logos/sheets.svg'),
    title: 'Sheets',
    description: 'Data App: Read and write to Sheets with a fully typed API.',
    downloads: '891',
    hearts: '7',
  },
  {
    icon: require('../../public/logos/postgres.svg'),
    title: 'Postgres',
    description: 'Data App: Read and write to Postgres with a fully typed API.',
    downloads: '2,421',
    hearts: '44',
  },
  {
    icon: require('../../public/logos/gdocs.svg'),
    title: 'GDocs',
    description: 'Data App: Read and write to GDocs with a fully typed API.',
    downloads: '4,213',
    hearts: '12',
  },
  {
    icon: require('../../public/logos/confluence.svg'),
    title: 'Confluence',
    description: 'Data App: Read and write to Confluence with a fully typed API.',
    downloads: '923',
    hearts: '7',
  },
]
