{
  "swagger": "2.0",
  "info": {
    "version": "1.0.6",
    "title": "Slack Web API",
    "description": "One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.",
    "contact": {}
  },
  "host": "slack.com",
  "basePath": "/api",
  "securityDefinitions": {
    "auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://slack.com/oauth/authorize",
      "tokenUrl": "https://slack.com/api/oauth.access",
      "scopes": {
        "admin": "admin",
        "bot": "Bot user scope",
        "channels:history": "channels:history",
        "channels:read": "channels:read",
        "channels:write": "channels:write",
        "chat:write": "chat:write",
        "chat:write:bot": "Author messages as a bot",
        "chat:write:user": "chat:write:user",
        "conversations:history": "conversations:history",
        "conversations:read": "conversations:read",
        "conversations:write": "conversations:write",
        "dnd:read": "dnd:read",
        "dnd:write": "dnd:write",
        "emoji:read": "emoji:read",
        "files:read": "files:read",
        "files:write:user": "files:write:user",
        "groups:history": "groups:history",
        "groups:read": "groups:read",
        "groups:write": "groups:write",
        "identity.basic": "identity.basic",
        "im:history": "im:history",
        "im:read": "im:read",
        "im:write": "im:write",
        "links:write": "links:write",
        "mpim:history": "mpim:history",
        "mpim:read": "mpim:read",
        "mpim:write": "mpim:write",
        "none": "No scope required",
        "pins:read": "pins:read",
        "pins:write": "pins:write",
        "reactions:read": "reactions:read",
        "reactions:write": "reactions:write",
        "reminders:read": "reminders:read",
        "reminders:write": "reminders:write",
        "rtm:stream": "rtm:stream",
        "search:read": "search:read",
        "stars:read": "stars:read",
        "stars:write": "stars:write",
        "team:read": "team:read",
        "tokens.basic": "tokens.basic",
        "usergroups:read": "usergroups:read",
        "usergroups:write": "usergroups:write",
        "users.profile:read": "users.profile:read",
        "users.profile:write": "users.profile:write",
        "users:read": "users:read",
        "users:read.email": "users:read.email",
        "users:write": "users:write"
      }
    }
  },
  "schemes": ["https"],
  "paths": {
    "/api.test": {
      "get": {
        "description": "Checks API calling code.",
        "summary": "api_test",
        "tags": ["api"],
        "operationId": "ApiTestGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/apps.permissions.info": {
      "get": {
        "description": "Returns list of permissions this app has on a team.",
        "summary": "apps_permissions_info",
        "tags": ["apps.permissions"],
        "operationId": "AppsPermissionsInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/apps.permissions.request": {
      "get": {
        "description": "Allows an app to request additional scopes",
        "summary": "apps_permissions_request",
        "tags": ["apps.permissions"],
        "operationId": "AppsPermissionsRequestGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/apps.permissions.resources.list": {
      "get": {
        "description": "Returns list of resource grants this app has on a team.",
        "summary": "apps_permissions_resources_list",
        "tags": ["apps.permissions.resources"],
        "operationId": "AppsPermissionsResourcesListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/apps.permissions.scopes.list": {
      "get": {
        "description": "Returns list of scopes this app has on a team.",
        "summary": "apps_permissions_scopes_list",
        "tags": ["apps.permissions.scopes"],
        "operationId": "AppsPermissionsScopesListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/auth.revoke": {
      "get": {
        "description": "Revokes a token.",
        "summary": "auth_revoke",
        "tags": ["auth"],
        "operationId": "AuthRevokeGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/auth.test": {
      "get": {
        "description": "Checks authentication & identity.",
        "summary": "auth_test",
        "tags": ["auth"],
        "operationId": "AuthTestGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/bots.info": {
      "get": {
        "description": "Gets information about a bot user.",
        "summary": "bots_info",
        "tags": ["bots"],
        "operationId": "BotsInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["users:read"]
          }
        ]
      }
    },
    "/channels.archive": {
      "post": {
        "description": "Archives a channel.",
        "summary": "channels_archive",
        "tags": ["channels"],
        "operationId": "ChannelsArchivePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.create": {
      "post": {
        "description": "Creates a channel.",
        "summary": "channels_create",
        "tags": ["channels"],
        "operationId": "ChannelsCreatePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.history": {
      "get": {
        "description": "Fetches history of messages and events from a channel.",
        "summary": "channels_history",
        "tags": ["channels"],
        "operationId": "ChannelsHistoryGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:history"]
          }
        ]
      }
    },
    "/channels.info": {
      "get": {
        "description": "Gets information about a channel.",
        "summary": "channels_info",
        "tags": ["channels"],
        "operationId": "ChannelsInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:read"]
          }
        ]
      }
    },
    "/channels.invite": {
      "post": {
        "description": "Invites a user to a channel.",
        "summary": "channels_invite",
        "tags": ["channels"],
        "operationId": "ChannelsInvitePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.join": {
      "post": {
        "description": "Joins a channel, creating it if needed.",
        "summary": "channels_join",
        "tags": ["channels"],
        "operationId": "ChannelsJoinPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.kick": {
      "post": {
        "description": "Removes a user from a channel.",
        "summary": "channels_kick",
        "tags": ["channels"],
        "operationId": "ChannelsKickPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.leave": {
      "post": {
        "description": "Leaves a channel.",
        "summary": "channels_leave",
        "tags": ["channels"],
        "operationId": "ChannelsLeavePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.list": {
      "get": {
        "description": "Lists all channels in a Slack team.",
        "summary": "channels_list",
        "tags": ["channels"],
        "operationId": "ChannelsListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:read"]
          }
        ]
      }
    },
    "/channels.mark": {
      "post": {
        "description": "Sets the read cursor in a channel.",
        "summary": "channels_mark",
        "tags": ["channels"],
        "operationId": "ChannelsMarkPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.rename": {
      "post": {
        "description": "Renames a channel.",
        "summary": "channels_rename",
        "tags": ["channels"],
        "operationId": "ChannelsRenamePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.replies": {
      "get": {
        "description": "Retrieve a thread of messages posted to a channel",
        "summary": "channels_replies",
        "tags": ["channels"],
        "operationId": "ChannelsRepliesGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:history"]
          }
        ]
      }
    },
    "/channels.setPurpose": {
      "post": {
        "description": "Sets the purpose for a channel.",
        "summary": "channels_setPurpose",
        "tags": ["channels"],
        "operationId": "ChannelsSetPurposePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.setTopic": {
      "post": {
        "description": "Sets the topic for a channel.",
        "summary": "channels_setTopic",
        "tags": ["channels"],
        "operationId": "ChannelsSetTopicPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/channels.unarchive": {
      "post": {
        "description": "Unarchives a channel.",
        "summary": "channels_unarchive",
        "tags": ["channels"],
        "operationId": "ChannelsUnarchivePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/chat.delete": {
      "post": {
        "description": "Deletes a message.",
        "summary": "chat_delete",
        "tags": ["chat"],
        "operationId": "ChatDeletePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["chat:write:user", "chat:write:bot"]
          }
        ]
      }
    },
    "/chat.getPermalink": {
      "get": {
        "description": "Retrieve a permalink URL for a specific extant message",
        "summary": "chat_getPermalink",
        "tags": ["chat"],
        "operationId": "ChatGetPermalinkGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/chat.meMessage": {
      "post": {
        "description": "Share a me message into a channel.",
        "summary": "chat_meMessage",
        "tags": ["chat"],
        "operationId": "ChatMeMessagePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["chat:write:user"]
          }
        ]
      }
    },
    "/chat.postEphemeral": {
      "post": {
        "description": "Sends an ephemeral message to a user in a channel.",
        "summary": "chat_postEphemeral",
        "tags": ["chat"],
        "operationId": "ChatPostEphemeralPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["chat:write:user", "chat:write:bot"]
          }
        ]
      }
    },
    "/chat.postMessage": {
      "post": {
        "description": "Sends a message to a channel.",
        "summary": "chat_postMessage",
        "tags": ["chat"],
        "operationId": "ChatPostMessagePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["chat:write:user", "chat:write:bot"]
          }
        ]
      }
    },
    "/chat.unfurl": {
      "post": {
        "description": "Provide custom unfurl behavior for user-posted URLs",
        "summary": "chat_unfurl",
        "tags": ["chat"],
        "operationId": "ChatUnfurlPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["links:write"]
          }
        ]
      }
    },
    "/chat.update": {
      "post": {
        "description": "Updates a message.",
        "summary": "chat_update",
        "tags": ["chat"],
        "operationId": "ChatUpdatePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["chat:write:user", "chat:write:bot"]
          }
        ]
      }
    },
    "/conversations.archive": {
      "post": {
        "description": "Archives a conversation.",
        "summary": "conversations_archive",
        "tags": ["conversations"],
        "operationId": "ConversationsArchivePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.close": {
      "post": {
        "description": "Closes a direct message or multi-person direct message.",
        "summary": "conversations_close",
        "tags": ["conversations"],
        "operationId": "ConversationsClosePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.create": {
      "post": {
        "description": "Initiates a public or private channel-based conversation",
        "summary": "conversations_create",
        "tags": ["conversations"],
        "operationId": "ConversationsCreatePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.history": {
      "get": {
        "description": "Fetches a conversation's history of messages and events.",
        "summary": "conversations_history",
        "tags": ["conversations"],
        "operationId": "ConversationsHistoryGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:history", "groups:history", "im:history", "mpim:history"]
          }
        ]
      }
    },
    "/conversations.info": {
      "get": {
        "description": "Retrieve information about a conversation.",
        "summary": "conversations_info",
        "tags": ["conversations"],
        "operationId": "ConversationsInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:read", "groups:read", "im:read", "mpim:read"]
          }
        ]
      }
    },
    "/conversations.invite": {
      "post": {
        "description": "Invites users to a channel.",
        "summary": "conversations_invite",
        "tags": ["conversations"],
        "operationId": "ConversationsInvitePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.join": {
      "post": {
        "description": "Joins an existing conversation.",
        "summary": "conversations_join",
        "tags": ["conversations"],
        "operationId": "ConversationsJoinPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write"]
          }
        ]
      }
    },
    "/conversations.kick": {
      "post": {
        "description": "Removes a user from a conversation.",
        "summary": "conversations_kick",
        "tags": ["conversations"],
        "operationId": "ConversationsKickPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.leave": {
      "post": {
        "description": "Leaves a conversation.",
        "summary": "conversations_leave",
        "tags": ["conversations"],
        "operationId": "ConversationsLeavePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.list": {
      "get": {
        "description": "Lists all channels in a Slack team.",
        "summary": "conversations_list",
        "tags": ["conversations"],
        "operationId": "ConversationsListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:read", "groups:read", "im:read", "mpim:read"]
          }
        ]
      }
    },
    "/conversations.members": {
      "get": {
        "description": "Retrieve members of a conversation.",
        "summary": "conversations_members",
        "tags": ["conversations"],
        "operationId": "ConversationsMembersGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:read", "groups:read", "im:read", "mpim:read"]
          }
        ]
      }
    },
    "/conversations.open": {
      "post": {
        "description": "Opens or resumes a direct message or multi-person direct message.",
        "summary": "conversations_open",
        "tags": ["conversations"],
        "operationId": "ConversationsOpenPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.rename": {
      "post": {
        "description": "Renames a conversation.",
        "summary": "conversations_rename",
        "tags": ["conversations"],
        "operationId": "ConversationsRenamePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.replies": {
      "get": {
        "description": "Retrieve a thread of messages posted to a conversation",
        "summary": "conversations_replies",
        "tags": ["conversations"],
        "operationId": "ConversationsRepliesGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:history", "groups:history", "im:history", "mpim:history"]
          }
        ]
      }
    },
    "/conversations.setPurpose": {
      "post": {
        "description": "Sets the purpose for a conversation.",
        "summary": "conversations_setPurpose",
        "tags": ["conversations"],
        "operationId": "ConversationsSetPurposePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.setTopic": {
      "post": {
        "description": "Sets the topic for a conversation.",
        "summary": "conversations_setTopic",
        "tags": ["conversations"],
        "operationId": "ConversationsSetTopicPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/conversations.unarchive": {
      "post": {
        "description": "Reverses conversation archival.",
        "summary": "conversations_unarchive",
        "tags": ["conversations"],
        "operationId": "ConversationsUnarchivePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:write", "groups:write", "im:write", "mpim:write"]
          }
        ]
      }
    },
    "/dialog.open": {
      "get": {
        "description": "Open a dialog with a user",
        "summary": "dialog_open",
        "tags": ["dialog"],
        "operationId": "DialogOpenGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/dnd.endDnd": {
      "post": {
        "description": "Ends the current user's Do Not Disturb session immediately.",
        "summary": "dnd_endDnd",
        "tags": ["dnd"],
        "operationId": "DndEndDndPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["dnd:write"]
          }
        ]
      }
    },
    "/dnd.endSnooze": {
      "post": {
        "description": "Ends the current user's snooze mode immediately.",
        "summary": "dnd_endSnooze",
        "tags": ["dnd"],
        "operationId": "DndEndSnoozePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["dnd:write"]
          }
        ]
      }
    },
    "/dnd.info": {
      "get": {
        "description": "Retrieves a user's current Do Not Disturb status.",
        "summary": "dnd_info",
        "tags": ["dnd"],
        "operationId": "DndInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["dnd:read"]
          }
        ]
      }
    },
    "/dnd.setSnooze": {
      "post": {
        "description": "Turns on Do Not Disturb mode for the current user, or changes its duration.",
        "summary": "dnd_setSnooze",
        "tags": ["dnd"],
        "operationId": "DndSetSnoozePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["dnd:write"]
          }
        ]
      }
    },
    "/dnd.teamInfo": {
      "get": {
        "description": "Retrieves the Do Not Disturb status for users on a team.",
        "summary": "dnd_teamInfo",
        "tags": ["dnd"],
        "operationId": "DndTeamInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["dnd:read"]
          }
        ]
      }
    },
    "/emoji.list": {
      "get": {
        "description": "Lists custom emoji for a team.",
        "summary": "emoji_list",
        "tags": ["emoji"],
        "operationId": "EmojiListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["emoji:read"]
          }
        ]
      }
    },
    "/files.comments.add": {
      "post": {
        "description": "Add a comment to an existing file.",
        "summary": "files_comments_add",
        "tags": ["files.comments"],
        "operationId": "FilesCommentsAddPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:write:user"]
          }
        ]
      }
    },
    "/files.comments.delete": {
      "post": {
        "description": "Deletes an existing comment on a file.",
        "summary": "files_comments_delete",
        "tags": ["files.comments"],
        "operationId": "FilesCommentsDeletePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:write:user"]
          }
        ]
      }
    },
    "/files.comments.edit": {
      "post": {
        "description": "Edit an existing file comment.",
        "summary": "files_comments_edit",
        "tags": ["files.comments"],
        "operationId": "FilesCommentsEditPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:write:user"]
          }
        ]
      }
    },
    "/files.delete": {
      "post": {
        "description": "Deletes a file.",
        "summary": "files_delete",
        "tags": ["files"],
        "operationId": "FilesDeletePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:write:user"]
          }
        ]
      }
    },
    "/files.info": {
      "get": {
        "description": "Gets information about a team file.",
        "summary": "files_info",
        "tags": ["files"],
        "operationId": "FilesInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:read"]
          }
        ]
      }
    },
    "/files.list": {
      "get": {
        "description": "Lists & filters team files.",
        "summary": "files_list",
        "tags": ["files"],
        "operationId": "FilesListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:read"]
          }
        ]
      }
    },
    "/files.revokePublicURL": {
      "post": {
        "description": "Revokes public/external sharing access for a file",
        "summary": "files_revokePublicURL",
        "tags": ["files"],
        "operationId": "FilesRevokePublicURLPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:write:user"]
          }
        ]
      }
    },
    "/files.sharedPublicURL": {
      "post": {
        "description": "Enables a file for public/external sharing.",
        "summary": "files_sharedPublicURL",
        "tags": ["files"],
        "operationId": "FilesSharedPublicURLPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:write:user"]
          }
        ]
      }
    },
    "/files.upload": {
      "post": {
        "description": "Uploads or creates a file.",
        "summary": "files_upload",
        "tags": ["files"],
        "operationId": "FilesUploadPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["files:write:user"]
          }
        ]
      }
    },
    "/groups.archive": {
      "post": {
        "description": "Archives a private channel.",
        "summary": "groups_archive",
        "tags": ["groups"],
        "operationId": "GroupsArchivePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.create": {
      "post": {
        "description": "Creates a private channel.",
        "summary": "groups_create",
        "tags": ["groups"],
        "operationId": "GroupsCreatePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.createChild": {
      "post": {
        "description": "Clones and archives a private channel.",
        "summary": "groups_createChild",
        "tags": ["groups"],
        "operationId": "GroupsCreateChildPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.history": {
      "get": {
        "description": "Fetches history of messages and events from a private channel.",
        "summary": "groups_history",
        "tags": ["groups"],
        "operationId": "GroupsHistoryGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:history"]
          }
        ]
      }
    },
    "/groups.info": {
      "get": {
        "description": "Gets information about a private channel.",
        "summary": "groups_info",
        "tags": ["groups"],
        "operationId": "GroupsInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:read"]
          }
        ]
      }
    },
    "/groups.invite": {
      "post": {
        "description": "Invites a user to a private channel.",
        "summary": "groups_invite",
        "tags": ["groups"],
        "operationId": "GroupsInvitePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.kick": {
      "post": {
        "description": "Removes a user from a private channel.",
        "summary": "groups_kick",
        "tags": ["groups"],
        "operationId": "GroupsKickPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.leave": {
      "post": {
        "description": "Leaves a private channel.",
        "summary": "groups_leave",
        "tags": ["groups"],
        "operationId": "GroupsLeavePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.list": {
      "get": {
        "description": "Lists private channels that the calling user has access to.",
        "summary": "groups_list",
        "tags": ["groups"],
        "operationId": "GroupsListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:read"]
          }
        ]
      }
    },
    "/groups.mark": {
      "post": {
        "description": "Sets the read cursor in a private channel.",
        "summary": "groups_mark",
        "tags": ["groups"],
        "operationId": "GroupsMarkPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.open": {
      "post": {
        "description": "Opens a private channel.",
        "summary": "groups_open",
        "tags": ["groups"],
        "operationId": "GroupsOpenPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.rename": {
      "post": {
        "description": "Renames a private channel.",
        "summary": "groups_rename",
        "tags": ["groups"],
        "operationId": "GroupsRenamePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.replies": {
      "get": {
        "description": "Retrieve a thread of messages posted to a private channel",
        "summary": "groups_replies",
        "tags": ["groups"],
        "operationId": "GroupsRepliesGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:history"]
          }
        ]
      }
    },
    "/groups.setPurpose": {
      "post": {
        "description": "Sets the purpose for a private channel.",
        "summary": "groups_setPurpose",
        "tags": ["groups"],
        "operationId": "GroupsSetPurposePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.setTopic": {
      "post": {
        "description": "Sets the topic for a private channel.",
        "summary": "groups_setTopic",
        "tags": ["groups"],
        "operationId": "GroupsSetTopicPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/groups.unarchive": {
      "post": {
        "description": "Unarchives a private channel.",
        "summary": "groups_unarchive",
        "tags": ["groups"],
        "operationId": "GroupsUnarchivePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["groups:write"]
          }
        ]
      }
    },
    "/im.close": {
      "post": {
        "description": "Close a direct message channel.",
        "summary": "im_close",
        "tags": ["im"],
        "operationId": "ImClosePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["im:write"]
          }
        ]
      }
    },
    "/im.history": {
      "get": {
        "description": "Fetches history of messages and events from direct message channel.",
        "summary": "im_history",
        "tags": ["im"],
        "operationId": "ImHistoryGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["im:history"]
          }
        ]
      }
    },
    "/im.list": {
      "get": {
        "description": "Lists direct message channels for the calling user.",
        "summary": "im_list",
        "tags": ["im"],
        "operationId": "ImListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["im:read"]
          }
        ]
      }
    },
    "/im.mark": {
      "post": {
        "description": "Sets the read cursor in a direct message channel.",
        "summary": "im_mark",
        "tags": ["im"],
        "operationId": "ImMarkPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["im:write"]
          }
        ]
      }
    },
    "/im.open": {
      "post": {
        "description": "Opens a direct message channel.",
        "summary": "im_open",
        "tags": ["im"],
        "operationId": "ImOpenPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["im:write"]
          }
        ]
      }
    },
    "/im.replies": {
      "get": {
        "description": "Retrieve a thread of messages posted to a direct message conversation",
        "summary": "im_replies",
        "tags": ["im"],
        "operationId": "ImRepliesGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["im:history"]
          }
        ]
      }
    },
    "/migration.exchange": {
      "get": {
        "description": "For Enterprise Grid workspaces, map local user IDs to global user IDs",
        "summary": "migration_exchange",
        "tags": ["migration"],
        "operationId": "MigrationExchangeGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["tokens.basic"]
          }
        ]
      }
    },
    "/mpim.close": {
      "post": {
        "description": "Closes a multiparty direct message channel.",
        "summary": "mpim_close",
        "tags": ["mpim"],
        "operationId": "MpimClosePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["mpim:write"]
          }
        ]
      }
    },
    "/mpim.history": {
      "get": {
        "description": "Fetches history of messages and events from a multiparty direct message.",
        "summary": "mpim_history",
        "tags": ["mpim"],
        "operationId": "MpimHistoryGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["mpim:history"]
          }
        ]
      }
    },
    "/mpim.list": {
      "get": {
        "description": "Lists multiparty direct message channels for the calling user.",
        "summary": "mpim_list",
        "tags": ["mpim"],
        "operationId": "MpimListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["mpim:read"]
          }
        ]
      }
    },
    "/mpim.mark": {
      "post": {
        "description": "Sets the read cursor in a multiparty direct message channel.",
        "summary": "mpim_mark",
        "tags": ["mpim"],
        "operationId": "MpimMarkPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["mpim:write"]
          }
        ]
      }
    },
    "/mpim.open": {
      "post": {
        "description": "This method opens a multiparty direct message.",
        "summary": "mpim_open",
        "tags": ["mpim"],
        "operationId": "MpimOpenPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["mpim:write"]
          }
        ]
      }
    },
    "/mpim.replies": {
      "get": {
        "description": "Retrieve a thread of messages posted to a direct message conversation from a multiparty direct message.",
        "summary": "mpim_replies",
        "tags": ["mpim"],
        "operationId": "MpimRepliesGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["mpim:history"]
          }
        ]
      }
    },
    "/oauth.access": {
      "get": {
        "description": "Exchanges a temporary OAuth verifier code for an access token.",
        "summary": "oauth_access",
        "tags": ["oauth"],
        "operationId": "OauthAccessGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/oauth.token": {
      "get": {
        "description": "Exchanges a temporary OAuth verifier code for a workspace token.",
        "summary": "oauth_token",
        "tags": ["oauth"],
        "operationId": "OauthTokenGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["none"]
          }
        ]
      }
    },
    "/pins.add": {
      "post": {
        "description": "Pins an item to a channel.",
        "summary": "pins_add",
        "tags": ["pins"],
        "operationId": "PinsAddPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["pins:write"]
          }
        ]
      }
    },
    "/pins.list": {
      "get": {
        "description": "Lists items pinned to a channel.",
        "summary": "pins_list",
        "tags": ["pins"],
        "operationId": "PinsListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["pins:read"]
          }
        ]
      }
    },
    "/pins.remove": {
      "post": {
        "description": "Un-pins an item from a channel.",
        "summary": "pins_remove",
        "tags": ["pins"],
        "operationId": "PinsRemovePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["pins:write"]
          }
        ]
      }
    },
    "/reactions.add": {
      "post": {
        "description": "Adds a reaction to an item.",
        "summary": "reactions_add",
        "tags": ["reactions"],
        "operationId": "ReactionsAddPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["reactions:write"]
          }
        ]
      }
    },
    "/reactions.get": {
      "get": {
        "description": "Gets reactions for an item.",
        "summary": "reactions_get",
        "tags": ["reactions"],
        "operationId": "ReactionsGetGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["reactions:read"]
          }
        ]
      }
    },
    "/reactions.list": {
      "get": {
        "description": "Lists reactions made by a user.",
        "summary": "reactions_list",
        "tags": ["reactions"],
        "operationId": "ReactionsListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["reactions:read"]
          }
        ]
      }
    },
    "/reactions.remove": {
      "post": {
        "description": "Removes a reaction from an item.",
        "summary": "reactions_remove",
        "tags": ["reactions"],
        "operationId": "ReactionsRemovePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["reactions:write"]
          }
        ]
      }
    },
    "/reminders.add": {
      "post": {
        "description": "Creates a reminder.",
        "summary": "reminders_add",
        "tags": ["reminders"],
        "operationId": "RemindersAddPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["reminders:write"]
          }
        ]
      }
    },
    "/reminders.complete": {
      "post": {
        "description": "Marks a reminder as complete.",
        "summary": "reminders_complete",
        "tags": ["reminders"],
        "operationId": "RemindersCompletePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["reminders:write"]
          }
        ]
      }
    },
    "/reminders.delete": {
      "post": {
        "description": "Deletes a reminder.",
        "summary": "reminders_delete",
        "tags": ["reminders"],
        "operationId": "RemindersDeletePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["reminders:write"]
          }
        ]
      }
    },
    "/reminders.info": {
      "get": {
        "description": "Gets information about a reminder.",
        "summary": "reminders_info",
        "tags": ["reminders"],
        "operationId": "RemindersInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["reminders:read"]
          }
        ]
      }
    },
    "/reminders.list": {
      "get": {
        "description": "Lists all reminders created by or for a given user.",
        "summary": "reminders_list",
        "tags": ["reminders"],
        "operationId": "RemindersListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["reminders:read"]
          }
        ]
      }
    },
    "/rtm.connect": {
      "get": {
        "description": "Starts a Real Time Messaging session.",
        "summary": "rtm_connect",
        "tags": ["rtm"],
        "operationId": "RtmConnectGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["rtm:stream"]
          }
        ]
      }
    },
    "/rtm.start": {
      "get": {
        "description": "Starts a Real Time Messaging session.",
        "summary": "rtm_start",
        "tags": ["rtm"],
        "operationId": "RtmStartGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["rtm:stream"]
          }
        ]
      }
    },
    "/search.all": {
      "get": {
        "description": "Searches for messages and files matching a query.",
        "summary": "search_all",
        "tags": ["search"],
        "operationId": "SearchAllGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["search:read"]
          }
        ]
      }
    },
    "/search.files": {
      "get": {
        "description": "Searches for files matching a query.",
        "summary": "search_files",
        "tags": ["search"],
        "operationId": "SearchFilesGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["search:read"]
          }
        ]
      }
    },
    "/search.messages": {
      "get": {
        "description": "Searches for messages matching a query.",
        "summary": "search_messages",
        "tags": ["search"],
        "operationId": "SearchMessagesGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["search:read"]
          }
        ]
      }
    },
    "/stars.add": {
      "post": {
        "description": "Adds a star to an item.",
        "summary": "stars_add",
        "tags": ["stars"],
        "operationId": "StarsAddPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["stars:write"]
          }
        ]
      }
    },
    "/stars.list": {
      "get": {
        "description": "Lists stars for a user.",
        "summary": "stars_list",
        "tags": ["stars"],
        "operationId": "StarsListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["stars:read"]
          }
        ]
      }
    },
    "/stars.remove": {
      "post": {
        "description": "Removes a star from an item.",
        "summary": "stars_remove",
        "tags": ["stars"],
        "operationId": "StarsRemovePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["stars:write"]
          }
        ]
      }
    },
    "/team.accessLogs": {
      "get": {
        "description": "Gets the access logs for the current team.",
        "summary": "team_accessLogs",
        "tags": ["team"],
        "operationId": "TeamAccessLogsGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["admin"]
          }
        ]
      }
    },
    "/team.billableInfo": {
      "get": {
        "description": "Gets billable users information for the current team.",
        "summary": "team_billableInfo",
        "tags": ["team"],
        "operationId": "TeamBillableInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["admin"]
          }
        ]
      }
    },
    "/team.info": {
      "get": {
        "description": "Gets information about the current team.",
        "summary": "team_info",
        "tags": ["team"],
        "operationId": "TeamInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["team:read"]
          }
        ]
      }
    },
    "/team.integrationLogs": {
      "get": {
        "description": "Gets the integration logs for the current team.",
        "summary": "team_integrationLogs",
        "tags": ["team"],
        "operationId": "TeamIntegrationLogsGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["admin"]
          }
        ]
      }
    },
    "/team.profile.get": {
      "get": {
        "description": "Retrieve a team's profile.",
        "summary": "team_profile_get",
        "tags": ["team.profile"],
        "operationId": "TeamProfileGetGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["users.profile:read"]
          }
        ]
      }
    },
    "/usergroups.create": {
      "post": {
        "description": "Create a User Group",
        "summary": "usergroups_create",
        "tags": ["usergroups"],
        "operationId": "UsergroupsCreatePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["usergroups:write"]
          }
        ]
      }
    },
    "/usergroups.disable": {
      "post": {
        "description": "Disable an existing User Group",
        "summary": "usergroups_disable",
        "tags": ["usergroups"],
        "operationId": "UsergroupsDisablePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["usergroups:write"]
          }
        ]
      }
    },
    "/usergroups.enable": {
      "post": {
        "description": "Enable a User Group",
        "summary": "usergroups_enable",
        "tags": ["usergroups"],
        "operationId": "UsergroupsEnablePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["usergroups:write"]
          }
        ]
      }
    },
    "/usergroups.list": {
      "get": {
        "description": "List all User Groups for a team",
        "summary": "usergroups_list",
        "tags": ["usergroups"],
        "operationId": "UsergroupsListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["usergroups:read"]
          }
        ]
      }
    },
    "/usergroups.update": {
      "post": {
        "description": "Update an existing User Group",
        "summary": "usergroups_update",
        "tags": ["usergroups"],
        "operationId": "UsergroupsUpdatePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["usergroups:write"]
          }
        ]
      }
    },
    "/usergroups.users.list": {
      "get": {
        "description": "List all users in a User Group",
        "summary": "usergroups_users_list",
        "tags": ["usergroups.users"],
        "operationId": "UsergroupsUsersListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["usergroups:read"]
          }
        ]
      }
    },
    "/usergroups.users.update": {
      "post": {
        "description": "Update the list of users for a User Group",
        "summary": "usergroups_users_update",
        "tags": ["usergroups.users"],
        "operationId": "UsergroupsUsersUpdatePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["usergroups:write"]
          }
        ]
      }
    },
    "/users.conversations": {
      "get": {
        "description": "List conversations the calling user may access.",
        "summary": "users_conversations",
        "tags": ["users"],
        "operationId": "UsersConversationsGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["channels:read", "groups:read", "im:read", "mpim:read"]
          }
        ]
      }
    },
    "/users.deletePhoto": {
      "post": {
        "description": "Delete the user profile photo",
        "summary": "users_deletePhoto",
        "tags": ["users"],
        "operationId": "UsersDeletePhotoPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["users.profile:write"]
          }
        ]
      }
    },
    "/users.getPresence": {
      "get": {
        "description": "Gets user presence information.",
        "summary": "users_getPresence",
        "tags": ["users"],
        "operationId": "UsersGetPresenceGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["users:read"]
          }
        ]
      }
    },
    "/users.identity": {
      "get": {
        "description": "Get a user's identity.",
        "summary": "users_identity",
        "tags": ["users"],
        "operationId": "UsersIdentityGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["identity.basic"]
          }
        ]
      }
    },
    "/users.info": {
      "get": {
        "description": "Gets information about a user.",
        "summary": "users_info",
        "tags": ["users"],
        "operationId": "UsersInfoGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["users:read"]
          }
        ]
      }
    },
    "/users.list": {
      "get": {
        "description": "Lists all users in a Slack team.",
        "summary": "users_list",
        "tags": ["users"],
        "operationId": "UsersListGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["users:read"]
          }
        ]
      }
    },
    "/users.lookupByEmail": {
      "get": {
        "description": "Find a user with an email address.",
        "summary": "users_lookupByEmail",
        "tags": ["users"],
        "operationId": "UsersLookupByEmailGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["users:read.email"]
          }
        ]
      }
    },
    "/users.setActive": {
      "post": {
        "description": "Marked a user as active. Deprecated and non-functional.",
        "summary": "users_setActive",
        "tags": ["users"],
        "operationId": "UsersSetActivePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["users:write"]
          }
        ]
      }
    },
    "/users.setPhoto": {
      "post": {
        "description": "Set the user profile photo",
        "summary": "users_setPhoto",
        "tags": ["users"],
        "operationId": "UsersSetPhotoPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["users.profile:write"]
          }
        ]
      }
    },
    "/users.setPresence": {
      "post": {
        "description": "Manually sets user presence.",
        "summary": "users_setPresence",
        "tags": ["users"],
        "operationId": "UsersSetPresencePost",
        "deprecated": false,
        "security": [
          {
            "auth": ["users:write"]
          }
        ]
      }
    },
    "/users.profile.get": {
      "get": {
        "description": "Retrieves a user's profile information.",
        "summary": "users_profile_get",
        "tags": ["users.profile"],
        "operationId": "UsersProfileGetGet",
        "deprecated": false,
        "security": [
          {
            "auth": ["users.profile:read"]
          }
        ]
      }
    },
    "/users.profile.set": {
      "post": {
        "description": "Set the profile information for a user.",
        "summary": "users_profile_set",
        "tags": ["users.profile"],
        "operationId": "UsersProfileSetPost",
        "deprecated": false,
        "security": [
          {
            "auth": ["users.profile:write"]
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "api",
      "description": ""
    },
    {
      "name": "apps.permissions",
      "description": ""
    },
    {
      "name": "apps.permissions.resources",
      "description": ""
    },
    {
      "name": "apps.permissions.scopes",
      "description": ""
    },
    {
      "name": "auth",
      "description": ""
    },
    {
      "name": "bots",
      "description": ""
    },
    {
      "name": "channels",
      "description": ""
    },
    {
      "name": "chat",
      "description": ""
    },
    {
      "name": "conversations",
      "description": ""
    },
    {
      "name": "dialog",
      "description": ""
    },
    {
      "name": "dnd",
      "description": ""
    },
    {
      "name": "emoji",
      "description": ""
    },
    {
      "name": "files.comments",
      "description": ""
    },
    {
      "name": "files",
      "description": ""
    },
    {
      "name": "groups",
      "description": ""
    },
    {
      "name": "im",
      "description": ""
    },
    {
      "name": "migration",
      "description": ""
    },
    {
      "name": "mpim",
      "description": ""
    },
    {
      "name": "oauth",
      "description": ""
    },
    {
      "name": "pins",
      "description": ""
    },
    {
      "name": "reactions",
      "description": ""
    },
    {
      "name": "reminders",
      "description": ""
    },
    {
      "name": "rtm",
      "description": ""
    },
    {
      "name": "search",
      "description": ""
    },
    {
      "name": "stars",
      "description": ""
    },
    {
      "name": "team",
      "description": ""
    },
    {
      "name": "team.profile",
      "description": ""
    },
    {
      "name": "usergroups",
      "description": ""
    },
    {
      "name": "usergroups.users",
      "description": ""
    },
    {
      "name": "users",
      "description": ""
    },
    {
      "name": "users.profile",
      "description": ""
    }
  ]
}
