export { render } from './renderer/render'
export const App = 'APP'
export const Window = 'WINDOW'
export const Menu = 'MENU'
export const MenuItem = 'MENUITEM'
export const SubMenu = 'SUBMENU'
export const Text = 'TEXT'
