runAppleScript;
from;
'./runAppleScript';
getContext;
from;
'./getContext';
getAppSize;
from;
'./getAppSize';
open;
from;
'opn';
escapeAppleScriptString;
from;
'escape-string-applescript';
getExtensions;
from;
'./getExtensions';
getCrawler;
from;
'./getCrawler';
export const sleep = ms => new Promise(res => setTimeout(res, ms));
//# sourceMappingURL=index.js.map