export main from './main/sidebar'
export oramain from './oramain/sidebar'
export services from './services/sidebar'
export task from './task/sidebar'
export doc from './doc/sidebar'
export feed from './feed/sidebar'
export { MessageSidebar as message } from './message'
export person from './person/sidebar'
export mail from './mail/sidebar'
export { StanfordSidebar as stanford } from './stanford'
