export default `Jackson Palmer no longer thinks it’s funny to imitate Doge, the internet meme about a Shiba Inu dog whose awe-struck expressions and garbled syntax (e.g. “Wow. So pizza. Much delicious.”) made him a viral sensation several years ago.
But if he did, he might channel Doge to offer a few cautionary words for investors who are falling for cryptocurrency start-ups, Silicon Valley’s latest moneymaking craze:
Very bubble. Much scam. So avoid.
Mr. Palmer, the creator of Dogecoin, was an early fan of cryptocurrency, a form of encrypted digital money that is traded from person to person. He saw investors talking about Bitcoin, the oldest and best-known cryptocurrency, and wanted to find a way to poke fun at the hype surrounding the emerging technology.
So in 2013, he built his own cryptocurrency, a satirical mash-up that combined Bitcoin with the Doge meme he’d seen on social media. Mr. Palmer hoped to use Dogecoin to show the absurdity of wagering huge sums of money on unstable ventures.
But investors didn’t get the joke and bought Dogecoin anyway, bringing its market value as high as $400 million. Along the way, the currency became a magnet for greed and attracted a group of scammers and hackers who defrauded investors, hyped fake products, and left many of the currency’s original backers empty-handed.
Today, Mr. Palmer, 30, is one of the loudest voices warning that a similar fate might soon befall the entire cryptocurrency industry.
“What’s happening to crypto now is what happened to Dogecoin,” Mr. Palmer told me in a recent interview. “I’m worried that this time, it’s on a much grander scale.”
Already, there are signs of trouble on the horizon. This week, after Chinese authorities announced a crackdown on virtual currencies, the value of Bitcoin briefly tumbled 30 percent before partially recovering. The value of Dogecoin fell more than 50 percent last week. Its market value by midday Friday was about $100 million.
But there remains no bigger mania among tech investors than cryptocurrency, which some see as an eventual replacement for traditional, government-issued money. Even with the recent declines, the price of Bitcoin has more than tripled this year; another cryptocurrency, Ethereum, has gained more than 2,300 percent. The success of these currencies has minted a new class of “crypto-millionaires” and spawned hundreds of other digital currencies, called altcoins. In addition, it has given rise to an entire category of start-ups that take advantage of cryptocurrency’s public ledger system, known as the blockchain.
Many cryptocurrency start-ups have raised money through an initial coin offering, or I.C.O., a type of fund-raising campaign in which investors buy into a new venture using Bitcoin or another cryptocurrency and receive virtual “tokens” instead of stock or voting rights in the company. These tokens grant investors access to a product or service that will be built with the money raised in the I.C.O., such as cloud data storage or access to a new social network.
(If you’re having trouble picturing it: Imagine that a friend is building a casino and asks you to invest. In exchange, you get chips that can be used at the casino’s tables once it’s finished. Now imagine that the value of the chips isn’t fixed, and will instead fluctuate depending on the popularity of the casino, the number of other gamblers and the regulatory environment for casinos. Oh, and instead of a friend, imagine it’s a stranger on the internet who might be using a fake name, who might not actually know how to build a casino, and whom you probably can’t sue for fraud if he steals your money and uses it to buy a Porsche instead. That’s an I.C.O.)`
