apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    run: api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32099
  selector:
    run: api
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: api
    spec:
      imagePullSecrets:
        - name: docker-hub
      containers:
      - name: api
        image: index.docker.io/motion/starter-api:latest
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: couchdb
        - name: DB_PORT
          value: "5984"
        - name: DB_PROTOCOL
          value: http://
status: {}

