kind: Template
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: pad-api
      labels:
        run: pad-api
    spec:
      type: NodePort
      selector:
        run: pad-api
      ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 32099
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: pad-api
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            run: pad-api
        spec:
          imagePullSecrets:
            - name: docker-hub
          volumes:
            - name: app-code
              hostPath:
                path: $(PWD)/apps
          containers:
            - name: pad-api
              image: $(REGISTRY)/motion/starter-api:$(ENV)
              imagePullPolicy: Always
              volumeMounts:
              - mountPath: /repo/apps
                name: app-code
              ports:
              - containerPort: 3000
              env:
              - name: PORT
                value: "3000"
              - name: DB_HOST
                value: pad-couch
              - name: DB_PORT
                value: "5984"
              - name: DB_PROTOCOL
                value: http://
parameters:
  - name: ENV
    value: null
  - name: REGISTRY
    value: null
  - name: PWD
    value: null
