kind: Template
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: pad-api
      labels:
        run: pad-api
    spec:
      type: NodePort
      ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 32099
      selector:
        run: pad-api
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: pad-api
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            run: pad-api
        spec:
          imagePullSecrets:
            - name: docker-hub
          containers:
          - name: pad-api
            image: $(REGISTRY)/motion/starter-api:$(ENV)
            imagePullPolicy: Always
            resources: {}
            ports:
            - containerPort: 3000
            env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: couchdb
            - name: DB_PORT
              value: "5984"
            - name: DB_PROTOCOL
              value: http://
    status: {}
parameters:
  - name: ENV
    value: null
  - name: REGISTRY
    value: null
