---
kind: Service
apiVersion: v1
metadata:
  name: pad-api
  labels:
    run: pad-api
spec:
  type: NodePort
  selector:
    run: pad-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32099
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pad-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: pad-api
    spec:
      imagePullSecrets:
        - name: docker-hub
      volumes:
        - name: app-code
          hostPath:
            path: "{{PWD}}/apps"
      containers:
        - name: pad-api
          image: {{REGISTRY}}/motion/starter-api:{{ENV}}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /repo/apps
              name: app-code
          ports:
          - containerPort: 3000
          resources: {}
          env:
          - name: PORT
            value: "3000"
          - name: DB_HOSTNAME
            value: "{{DB_HOSTNAME}}"
          - name: DB_PORT
            value: "5984"
          - name: DB_PROTOCOL
            value: "{{DB_PROTOCOL}}"
          - name: DB_PUBLIC_URL
            value: "{{DB_PUBLIC_URL}}"
          - name: DB_USER
            value: "{{DB_USER}}"
          - name: DB_PASSWORD
            value: "{{DB_PASSWORD}}"
