apiVersion: v1
kind: Service
metadata:
  name: starter-api
  creationTimestamp: null
  labels:
    run: starter-api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32099
  selector:
    run: starter-api
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: starter-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: starter-api
    spec:
      imagePullSecrets:
        - name: docker-hub
      containers:
      - env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: starter-couchdb
        - name: DB_PORT
          value: "5984"
        - name: DB_PROTOCOL
          value: http://
        - name: DB_USER
        - name: DB_PASSWORD
        image: index.docker.io/motion/starter-api:latest
        imagePullPolicy: Always
        name: starter-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    run: starter-api-claim
  name: starter-api-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
