apiVersion: v1
kind: Service
metadata:
  name: starter-couchdb
  labels:
    run: starter-couchdb
spec:
  ports:
  - port: 5984
    targetPort: 5984
  selector:
    run: starter-couchdb
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: starter-couchdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: starter-couchdb
    spec:
      containers:
      - env:
        - name: DB_USER
        - name: DB_PASSWORD
        image: klaemo/couchdb:latest
        imagePullPolicy: IfNotPresent
        name: starter-couchdb
        ports:
        - containerPort: 5984
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    run: starter-couchdb-claim
  name: starter-couchdb-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
