apiVersion: v1
kind: Service
metadata:
  name: public
  labels:
    run: public
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    run: public
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: public
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: public
    spec:
      imagePullSecrets:
        - name: docker-hub
      containers:
      - name: public
        image: index.docker.io/motion/starter-public:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources: {}
status: {}

