apiVersion: v1
kind: Service
metadata:
  name: pad-public
  labels:
    run: pad-public
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
      name: http
  selector:
    run: pad-public
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pad-public
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: pad-public
    spec:
      imagePullSecrets:
        - name: docker-hub
      containers:
      - name: pad-public
        image: index.docker.io/motion/starter-public:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
status: {}

