apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: starter-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: starter-api
    spec:
      containers:
      - env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: starter-couchdb
        - name: DB_PORT
          value: "5984"
        - name: DB_PROTOCOL
          value: http://
        - name: DB_USER
        - name: DB_PASSWORD
        name: starter-api
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /repo/apps/api
          name: starter-api-claim0
      restartPolicy: Always
      volumes:
      - name: starter-api-claim0
        persistentVolumeClaim:
          claimName: starter-api-claim0
status: {}
