kind: Service
apiVersion: v1
metadata:
  name: pad-web
  labels:
    run: pad-web
spec:
  type: NodePort
  ports:
    - name: localhost
      port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    run: pad-web
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pad-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: pad-web
    spec:
      imagePullSecrets:
        - name: docker-hub
      volumes:
        - name: app-code
          hostPath:
            path: "{{PWD}}/apps"
      containers:
        - name: pad-web
          image: {{REGISTRY}}/motion/starter-web:{{ENV}}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /repo/apps
              name: app-code
          ports:
          - containerPort: 80
