kind: Service
apiVersion: v1
metadata:
  name: pad-web
  labels:
    run: pad-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
    - port: 3001
      targetPort: 3001
  selector:
    run: pad-web
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pad-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: pad-web
    spec:
      imagePullSecrets:
        - name: docker-hub
      containers:
      - name: pad-web
        image: {{REGISTRY}}/motion/starter-web:{{ENV}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
