kind: Service
apiVersion: v1
metadata:
  name: pad-web
  labels:
    run: pad-web
spec:
  type: NodePort
  ports:
    - name: localhost
      port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    run: pad-web
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pad-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: pad-web
    spec:
      imagePullSecrets:
        - name: docker-hub
      volumes:
        - name: app-code
          hostPath:
            path: "{{PWD}}/apps"
      containers:
        - name: pad-web
          image: {{REGISTRY}}/motion/starter-web:{{ENV}}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /repo/apps
              name: app-code
          ports:
          - containerPort: 80
          env:
          - name: PORT
            value: "3000"
          - name: DB_HOSTNAME
            value: "{{DB_HOSTNAME}}"
          - name: DB_PORT
            value: "5984"
          - name: DB_PROTOCOL
            value: "{{DB_PROTOCOL}}"
          - name: DB_PUBLIC_URL
            value: "{{DB_PUBLIC_URL}}"
          - name: DB_USER
            value: "{{DB_USER}}"
          - name: DB_PASSWORD
            value: "{{DB_PASSWORD}}"
