language: objective-c
cache: cocoapods
#before_install:
#- pod repo --silent update

xcode_workspace: Swindler.xcworkspace
xcode_scheme: Swindler

osx_image: xcode9
script: xcodebuild -workspace Swindler.xcworkspace -scheme Swindler build test
