storage: /tmp/.verdaccio-storage
plugins: ./plugins

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

auth:
  htpasswd:
    file: ./htpasswd

logs:
  - { type: stdout, format: pretty, level: warn }

max_body_size: 100mb
