storage: /tmp/.verdaccio-storage
plugins: ./plugins

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@mcro/*':
    #scoped packages
    access: $all
    publish: $all
    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: warn }

max_body_size: 100mb
