if(typeof Math.imul == "undefined" || (Math.imul(0xffffffff,5) == 0)) {
    Math.imul = function (a, b) {
        var ah  = (a >>> 16) & 0xffff;
        var al = a & 0xffff;
        var bh  = (b >>> 16) & 0xffff;
        var bl = b & 0xffff;
        // the shift by 0 fixes the sign on the high part
        // the final |0 converts the unsigned value into a signed value
        return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
    }
}


var f;
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function da(){var a=ea;return null!==a&&"argv"in a?a.argv:void 0};function fa(a,b){this.M=[];this.Ca=b;for(var c=!0,d=a.length-1;0<=d;d--){var e=a[d]|0;c&&e==b||(this.M[d]=e,c=!1)}}var ha={};function ia(a){if(-128<=a&&128>a){var b=ha[a];if(b)return b}b=new fa([a|0],0>a?-1:0);-128<=a&&128>a&&(ha[a]=b);return b}function ka(a){if(isNaN(a)||!isFinite(a))return la;if(0>a)return ka(-a).aa();for(var b=[],c=1,d=0;a>=c;d++)b[d]=a/c|0,c*=ma;return new fa(b,0)}var ma=4294967296,la=ia(0),na=ia(1),oa=ia(16777216);f=fa.prototype;
f.Zb=function(){return 0<this.M.length?this.M[0]:this.Ca};f.Ma=function(){if(this.ia())return-this.aa().Ma();for(var a=0,b=1,c=0;c<this.M.length;c++){var d=pa(this,c);a+=(0<=d?d:ma+d)*b;b*=ma}return a};
f.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(this.ta())return"0";if(this.ia())return"-"+this.aa().toString(a);for(var b=ka(Math.pow(a,6)),c=this,d="";;){var e=qa(c,b),g=(c.rb(e.multiply(b)).Zb()>>>0).toString(a);c=e;if(c.ta())return g+d;for(;6>g.length;)g="0"+g;d=""+g+d}};function pa(a,b){return 0>b?0:b<a.M.length?a.M[b]:a.Ca}f.ta=function(){if(0!=this.Ca)return!1;for(var a=0;a<this.M.length;a++)if(0!=this.M[a])return!1;return!0};f.ia=function(){return-1==this.Ca};
f.Tb=function(a){return 0<this.compare(a)};f.Ub=function(a){return 0<=this.compare(a)};f.Ab=function(){return 0>this.compare(oa)};f.Bb=function(a){return 0>=this.compare(a)};f.compare=function(a){a=this.rb(a);return a.ia()?-1:a.ta()?0:1};f.aa=function(){return this.Wb().add(na)};
f.add=function(a){for(var b=Math.max(this.M.length,a.M.length),c=[],d=0,e=0;e<=b;e++){var g=d+(pa(this,e)&65535)+(pa(a,e)&65535),h=(g>>>16)+(pa(this,e)>>>16)+(pa(a,e)>>>16);d=h>>>16;g&=65535;h&=65535;c[e]=h<<16|g}return new fa(c,c[c.length-1]&-2147483648?-1:0)};f.rb=function(a){return this.add(a.aa())};
f.multiply=function(a){if(this.ta()||a.ta())return la;if(this.ia())return a.ia()?this.aa().multiply(a.aa()):this.aa().multiply(a).aa();if(a.ia())return this.multiply(a.aa()).aa();if(this.Ab()&&a.Ab())return ka(this.Ma()*a.Ma());for(var b=this.M.length+a.M.length,c=[],d=0;d<2*b;d++)c[d]=0;for(d=0;d<this.M.length;d++)for(var e=0;e<a.M.length;e++){var g=pa(this,d)>>>16,h=pa(this,d)&65535,k=pa(a,e)>>>16,l=pa(a,e)&65535;c[2*d+2*e]+=h*l;ra(c,2*d+2*e);c[2*d+2*e+1]+=g*l;ra(c,2*d+2*e+1);c[2*d+2*e+1]+=h*k;
ra(c,2*d+2*e+1);c[2*d+2*e+2]+=g*k;ra(c,2*d+2*e+2)}for(d=0;d<b;d++)c[d]=c[2*d+1]<<16|c[2*d];for(d=b;d<2*b;d++)c[d]=0;return new fa(c,0)};function ra(a,b){for(;(a[b]&65535)!=a[b];)a[b+1]+=a[b]>>>16,a[b]&=65535,b++}
function qa(a,b){if(b.ta())throw Error("division by zero");if(a.ta())return la;if(a.ia())return b.ia()?qa(a.aa(),b.aa()):qa(a.aa(),b).aa();if(b.ia())return qa(a,b.aa()).aa();if(30<a.M.length){if(a.ia()||b.ia())throw Error("slowDivide_ only works with positive integers.");for(var c=na;b.Bb(a);)c=c.shiftLeft(1),b=b.shiftLeft(1);var d=c.Ga(1),e=b.Ga(1);b=b.Ga(2);for(c=c.Ga(2);!b.ta();){var g=e.add(b);g.Bb(a)&&(d=d.add(c),e=g);b=b.Ga(1);c=c.Ga(1)}return d}for(c=la;a.Ub(b);){d=Math.max(1,Math.floor(a.Ma()/
b.Ma()));e=Math.ceil(Math.log(d)/Math.LN2);e=48>=e?1:Math.pow(2,e-48);g=ka(d);for(var h=g.multiply(b);h.ia()||h.Tb(a);)d-=e,g=ka(d),h=g.multiply(b);g.ta()&&(g=na);c=c.add(g);a=a.rb(h)}return c}f.Wb=function(){for(var a=this.M.length,b=[],c=0;c<a;c++)b[c]=~this.M[c];return new fa(b,~this.Ca)};f.shiftLeft=function(a){var b=a>>5;a%=32;for(var c=this.M.length+b+(0<a?1:0),d=[],e=0;e<c;e++)d[e]=0<a?pa(this,e-b)<<a|pa(this,e-b-1)>>>32-a:pa(this,e-b);return new fa(d,this.Ca)};
f.Ga=function(a){var b=a>>5;a%=32;for(var c=this.M.length-b,d=[],e=0;e<c;e++)d[e]=0<a?pa(this,e+b)>>>a|pa(this,e+b+1)<<32-a:pa(this,e+b);return new fa(d,this.Ca)};function sa(a,b){null!=a&&this.append.apply(this,arguments)}f=sa.prototype;f.ya="";f.set=function(a){this.ya=""+a};f.append=function(a,b,c){this.ya+=String(a);if(null!=b)for(var d=1;d<arguments.length;d++)this.ya+=arguments[d];return this};f.clear=function(){this.ya=""};f.toString=function(){return this.ya};var ta={},ua;if("undefined"===typeof p)var p={};if("undefined"===typeof va)var va=null;if("undefined"===typeof wa)var wa=null;var ya=null;if("undefined"===typeof za)var za=null;function Aa(){return new Ba(null,5,[Ca,!0,Da,!0,Ea,!1,Fa,!1,Ga,null],null)}function q(a){return null!=a&&!1!==a}function Ha(a){return a instanceof Array}function Ia(a){return null==a?!0:!1===a?!0:!1}function t(a,b){return a[m(null==b?null:b)]?!0:a._?!0:!1}
function u(a,b){var c=null==b?null:b.constructor;c=q(q(c)?c.zb:c)?c.Ua:m(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function Ja(a){var b=a.Ua;return q(b)?b:""+w.c(a)}var Ka="undefined"!==typeof Symbol&&"function"===m(Symbol)?Symbol.iterator:"@@iterator";function La(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}function Ma(a){return Na(function(a,c){a.push(c);return a},[],a)}function Oa(){}function Pa(){}
var Qa=function Qa(a){if(null!=a&&null!=a.ba)return a.ba(a);var c=Qa[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=Qa._;if(null!=c)return c.c?c.c(a):c(a);throw u("ICounted.-count",a);};function Ra(){}var Sa=function Sa(a,b){if(null!=a&&null!=a.S)return a.S(a,b);var d=Sa[m(null==a?null:a)];if(null!=d)return d.f?d.f(a,b):d(a,b);d=Sa._;if(null!=d)return d.f?d.f(a,b):d(a,b);throw u("ICollection.-conj",a);};function Ta(){}
var z=function z(a){switch(arguments.length){case 2:return z.f(arguments[0],arguments[1]);case 3:return z.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",w.c(arguments.length)].join(""));}};z.f=function(a,b){if(null!=a&&null!=a.K)return a.K(a,b);var c=z[m(null==a?null:a)];if(null!=c)return c.f?c.f(a,b):c(a,b);c=z._;if(null!=c)return c.f?c.f(a,b):c(a,b);throw u("IIndexed.-nth",a);};
z.j=function(a,b,c){if(null!=a&&null!=a.la)return a.la(a,b,c);var d=z[m(null==a?null:a)];if(null!=d)return d.j?d.j(a,b,c):d(a,b,c);d=z._;if(null!=d)return d.j?d.j(a,b,c):d(a,b,c);throw u("IIndexed.-nth",a);};z.I=3;
var A=function A(a){if(null!=a&&null!=a.$)return a.$(a);var c=A[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=A._;if(null!=c)return c.c?c.c(a):c(a);throw u("ISeq.-first",a);},B=function B(a){if(null!=a&&null!=a.da)return a.da(a);var c=B[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=B._;if(null!=c)return c.c?c.c(a):c(a);throw u("ISeq.-rest",a);};function Ua(){}function Va(){}
var Wa=function Wa(a){switch(arguments.length){case 2:return Wa.f(arguments[0],arguments[1]);case 3:return Wa.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",w.c(arguments.length)].join(""));}};Wa.f=function(a,b){if(null!=a&&null!=a.T)return a.T(a,b);var c=Wa[m(null==a?null:a)];if(null!=c)return c.f?c.f(a,b):c(a,b);c=Wa._;if(null!=c)return c.f?c.f(a,b):c(a,b);throw u("ILookup.-lookup",a);};
Wa.j=function(a,b,c){if(null!=a&&null!=a.D)return a.D(a,b,c);var d=Wa[m(null==a?null:a)];if(null!=d)return d.j?d.j(a,b,c):d(a,b,c);d=Wa._;if(null!=d)return d.j?d.j(a,b,c):d(a,b,c);throw u("ILookup.-lookup",a);};Wa.I=3;var Xa=function Xa(a,b,c){if(null!=a&&null!=a.va)return a.va(a,b,c);var e=Xa[m(null==a?null:a)];if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);e=Xa._;if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);throw u("IAssociative.-assoc",a);};function Ya(){}function Za(){}
var $a=function $a(a){if(null!=a&&null!=a.ob)return a.ob();var c=$a[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=$a._;if(null!=c)return c.c?c.c(a):c(a);throw u("IMapEntry.-key",a);},ab=function ab(a){if(null!=a&&null!=a.pb)return a.pb();var c=ab[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=ab._;if(null!=c)return c.c?c.c(a):c(a);throw u("IMapEntry.-val",a);},bb=function bb(a){if(null!=a&&null!=a.Ra)return a.Ra(a);var c=bb[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=bb._;
if(null!=c)return c.c?c.c(a):c(a);throw u("IStack.-peek",a);},cb=function cb(a){if(null!=a&&null!=a.Sa)return a.Sa(a);var c=cb[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=cb._;if(null!=c)return c.c?c.c(a):c(a);throw u("IStack.-pop",a);};function db(){}var eb=function eb(a){if(null!=a&&null!=a.Ya)return a.Ya(a);var c=eb[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=eb._;if(null!=c)return c.c?c.c(a):c(a);throw u("IDeref.-deref",a);};function fb(){}
var gb=function gb(a){if(null!=a&&null!=a.P)return a.P(a);var c=gb[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=gb._;if(null!=c)return c.c?c.c(a):c(a);throw u("IMeta.-meta",a);},hb=function hb(a,b){if(null!=a&&null!=a.U)return a.U(a,b);var d=hb[m(null==a?null:a)];if(null!=d)return d.f?d.f(a,b):d(a,b);d=hb._;if(null!=d)return d.f?d.f(a,b):d(a,b);throw u("IWithMeta.-with-meta",a);};function ib(){}
var jb=function jb(a){switch(arguments.length){case 2:return jb.f(arguments[0],arguments[1]);case 3:return jb.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",w.c(arguments.length)].join(""));}};jb.f=function(a,b){if(null!=a&&null!=a.ca)return a.ca(a,b);var c=jb[m(null==a?null:a)];if(null!=c)return c.f?c.f(a,b):c(a,b);c=jb._;if(null!=c)return c.f?c.f(a,b):c(a,b);throw u("IReduce.-reduce",a);};
jb.j=function(a,b,c){if(null!=a&&null!=a.Z)return a.Z(a,b,c);var d=jb[m(null==a?null:a)];if(null!=d)return d.j?d.j(a,b,c):d(a,b,c);d=jb._;if(null!=d)return d.j?d.j(a,b,c):d(a,b,c);throw u("IReduce.-reduce",a);};jb.I=3;function kb(){}
var lb=function lb(a,b,c){if(null!=a&&null!=a.Oa)return a.Oa(a,b,c);var e=lb[m(null==a?null:a)];if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);e=lb._;if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);throw u("IKVReduce.-kv-reduce",a);},mb=function mb(a,b){if(null!=a&&null!=a.v)return a.v(a,b);var d=mb[m(null==a?null:a)];if(null!=d)return d.f?d.f(a,b):d(a,b);d=mb._;if(null!=d)return d.f?d.f(a,b):d(a,b);throw u("IEquiv.-equiv",a);},nb=function nb(a){if(null!=a&&null!=a.N)return a.N(a);var c=nb[m(null==a?null:a)];
if(null!=c)return c.c?c.c(a):c(a);c=nb._;if(null!=c)return c.c?c.c(a):c(a);throw u("IHash.-hash",a);};function ob(){}var pb=function pb(a){if(null!=a&&null!=a.L)return a.L(a);var c=pb[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=pb._;if(null!=c)return c.c?c.c(a):c(a);throw u("ISeqable.-seq",a);};function qb(){}function rb(){}function sb(){}
var C=function C(a,b){if(null!=a&&null!=a.yb)return a.yb(0,b);var d=C[m(null==a?null:a)];if(null!=d)return d.f?d.f(a,b):d(a,b);d=C._;if(null!=d)return d.f?d.f(a,b):d(a,b);throw u("IWriter.-write",a);},tb=function tb(a,b,c){if(null!=a&&null!=a.xb)return a.xb(0,b,c);var e=tb[m(null==a?null:a)];if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);e=tb._;if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);throw u("IWatchable.-notify-watches",a);},ub=function ub(a){if(null!=a&&null!=a.Ha)return a.Ha(a);var c=ub[m(null==a?
null:a)];if(null!=c)return c.c?c.c(a):c(a);c=ub._;if(null!=c)return c.c?c.c(a):c(a);throw u("IEditableCollection.-as-transient",a);},vb=function vb(a,b){if(null!=a&&null!=a.Ia)return a.Ia(a,b);var d=vb[m(null==a?null:a)];if(null!=d)return d.f?d.f(a,b):d(a,b);d=vb._;if(null!=d)return d.f?d.f(a,b):d(a,b);throw u("ITransientCollection.-conj!",a);},wb=function wb(a){if(null!=a&&null!=a.Ta)return a.Ta(a);var c=wb[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=wb._;if(null!=c)return c.c?c.c(a):
c(a);throw u("ITransientCollection.-persistent!",a);},xb=function xb(a,b,c){if(null!=a&&null!=a.za)return a.za(a,b,c);var e=xb[m(null==a?null:a)];if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);e=xb._;if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);throw u("ITransientAssociative.-assoc!",a);},yb=function yb(a){if(null!=a&&null!=a.tb)return a.tb();var c=yb[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=yb._;if(null!=c)return c.c?c.c(a):c(a);throw u("IChunk.-drop-first",a);},zb=function zb(a){if(null!=
a&&null!=a.Xa)return a.Xa(a);var c=zb[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=zb._;if(null!=c)return c.c?c.c(a):c(a);throw u("IChunkedSeq.-chunked-first",a);},Ab=function Ab(a){if(null!=a&&null!=a.Na)return a.Na(a);var c=Ab[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=Ab._;if(null!=c)return c.c?c.c(a):c(a);throw u("IChunkedSeq.-chunked-rest",a);},Bb=function Bb(a,b){if(null!=a&&null!=a.Jb)return a.Jb(a,b);var d=Bb[m(null==a?null:a)];if(null!=d)return d.f?d.f(a,b):d(a,b);d=
Bb._;if(null!=d)return d.f?d.f(a,b):d(a,b);throw u("IReset.-reset!",a);},E=function E(a){switch(arguments.length){case 2:return E.f(arguments[0],arguments[1]);case 3:return E.j(arguments[0],arguments[1],arguments[2]);case 4:return E.G(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return E.ha(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error(["Invalid arity: ",w.c(arguments.length)].join(""));}};
E.f=function(a,b){if(null!=a&&null!=a.Lb)return a.Lb(a,b);var c=E[m(null==a?null:a)];if(null!=c)return c.f?c.f(a,b):c(a,b);c=E._;if(null!=c)return c.f?c.f(a,b):c(a,b);throw u("ISwap.-swap!",a);};E.j=function(a,b,c){if(null!=a&&null!=a.Mb)return a.Mb(a,b,c);var d=E[m(null==a?null:a)];if(null!=d)return d.j?d.j(a,b,c):d(a,b,c);d=E._;if(null!=d)return d.j?d.j(a,b,c):d(a,b,c);throw u("ISwap.-swap!",a);};
E.G=function(a,b,c,d){if(null!=a&&null!=a.Nb)return a.Nb(a,b,c,d);var e=E[m(null==a?null:a)];if(null!=e)return e.G?e.G(a,b,c,d):e(a,b,c,d);e=E._;if(null!=e)return e.G?e.G(a,b,c,d):e(a,b,c,d);throw u("ISwap.-swap!",a);};E.ha=function(a,b,c,d,e){if(null!=a&&null!=a.Ob)return a.Ob(a,b,c,d,e);var g=E[m(null==a?null:a)];if(null!=g)return g.ha?g.ha(a,b,c,d,e):g(a,b,c,d,e);g=E._;if(null!=g)return g.ha?g.ha(a,b,c,d,e):g(a,b,c,d,e);throw u("ISwap.-swap!",a);};E.I=5;function Cb(){}
var Db=function Db(a){if(null!=a&&null!=a.sa)return a.sa(a);var c=Db[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=Db._;if(null!=c)return c.c?c.c(a):c(a);throw u("IIterable.-iterator",a);};function Eb(a){this.Yb=a;this.m=1073741824;this.A=0}Eb.prototype.yb=function(a,b){return this.Yb.append(b)};function Fb(a){var b=new sa;a.R(null,new Eb(b),Aa());return""+w.c(b)}
var Gb="undefined"!==typeof Math.imul&&0!==Math.imul(4294967295,5)?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function Hb(a){a=Gb(a|0,-862048943);return Gb(a<<15|a>>>-15,461845907)}function Ib(a,b){a=(a|0)^(b|0);return Gb(a<<13|a>>>-13,5)+-430675100|0}function Jb(a,b){a=(a|0)^b;a=Gb(a^a>>>16,-2048144789);a=Gb(a^a>>>13,-1028477387);return a^a>>>16}var Kb={},Lb=0;
function Mb(a){255<Lb&&(Kb={},Lb=0);if(null==a)return 0;var b=Kb[a];if("number"!==typeof b){a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b){var e=c+1;d=Gb(31,d)+a.charCodeAt(c);c=e}else{b=d;break a}else b=0;else b=0;Kb[a]=b;Lb+=1}return a=b}
function Nb(a){if(null!=a&&(a.m&4194304||p===a.fc))return a.N(null)^0;if("number"===typeof a){if(q(isFinite(a)))return Math.floor(a)%2147483647;switch(a){case Infinity:return 2146435072;case -Infinity:return-1048576;default:return 2146959360}}else return!0===a?a=1231:!1===a?a=1237:"string"===typeof a?(a=Mb(a),0!==a&&(a=Hb(a),a=Ib(0,a),a=Jb(a,4))):a=a instanceof Date?a.valueOf()^0:null==a?0:nb(a)^0,a}
function F(a){if(null==a)return null;if(null!=a&&(a.m&8388608||p===a.Kb))return a.L(null);if(Ha(a)||"string"===typeof a)return 0===a.length?null:new H(a,0,null);if(t(ob,a))return pb(a);throw Error([w.c(a)," is not ISeqable"].join(""));}function J(a){if(null==a)return null;if(null!=a&&(a.m&64||p===a.Qa))return a.$(null);a=F(a);return null==a?null:A(a)}function Ob(a){return null!=a?null!=a&&(a.m&64||p===a.Qa)?a.da(null):(a=F(a))?B(a):Pb:Pb}
function L(a){return null==a?null:null!=a&&(a.m&128||p===a.Pa)?a.X(null):F(Ob(a))}var N=function N(a){switch(arguments.length){case 1:return N.c(arguments[0]);case 2:return N.f(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return N.B(arguments[0],arguments[1],new H(c.slice(2),0,null))}};N.c=function(){return!0};N.f=function(a,b){return null==a?null==b:a===b||mb(a,b)};
N.B=function(a,b,c){for(;;)if(N.f(a,b))if(L(c))a=b,b=J(c),c=L(c);else return N.f(b,J(c));else return!1};N.H=function(a){var b=J(a),c=L(a);a=J(c);c=L(c);return N.B(b,a,c)};N.I=2;function Qb(a){this.s=a}Qb.prototype.next=function(){if(null!=this.s){var a=J(this.s);this.s=L(this.s);return{value:a,done:!1}}return{value:null,done:!0}};function O(a){return new Qb(F(a))}function Rb(a,b){a=Hb(a);a=Ib(0,a);return Jb(a,b)}
function Sb(a){var b=0,c=1;for(a=F(a);;)if(null!=a)b+=1,c=Gb(31,c)+Nb(J(a))|0,a=L(a);else return Rb(c,b)}var Tb=Rb(1,0);function Ub(a){var b=0,c=0;for(a=F(a);;)if(null!=a)b+=1,c=c+Nb(J(a))|0,a=L(a);else return Rb(c,b)}var Vb=Rb(0,0);Pa["null"]=!0;Qa["null"]=function(){return 0};Date.prototype.v=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};mb.number=function(a,b){return a===b};Oa["function"]=!0;fb["function"]=!0;gb["function"]=function(){return null};
nb._=function(a){return a[aa]||(a[aa]=++ba)};function Wb(a){this.ja=a;this.m=32768;this.A=0}Wb.prototype.Ya=function(){return this.ja};function Xb(a){return a instanceof Wb}function Yb(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c];e=b.f?b.f(e,g):b(e,g);if(Xb(e))return eb(e);c+=1}else return e}function Zb(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.f?b.f(c,g):b(c,g);if(Xb(c))return eb(c);d+=1}else return c}function $b(a){return null!=a?a.m&2||p===a.Db?!0:a.m?!1:t(Pa,a):t(Pa,a)}
function ac(a){return null!=a?a.m&16||p===a.vb?!0:a.m?!1:t(Ta,a):t(Ta,a)}function P(a,b,c){var d=Q(a);if(c>=d)return-1;!(0<c)&&0>c&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if(N.f(bc(a,c),b))return c;c+=1}else return-1}function R(a,b,c){var d=Q(a);if(0===d)return-1;0<c?(--d,c=d<c?d:c):c=0>c?d+c:c;for(;;)if(0<=c){if(N.f(bc(a,c),b))return c;--c}else return-1}function cc(a,b){this.h=a;this.i=b}cc.prototype.ea=function(){return this.i<this.h.length};
cc.prototype.next=function(){var a=this.h[this.i];this.i+=1;return a};function H(a,b,c){this.h=a;this.i=b;this.meta=c;this.m=166592766;this.A=139264}f=H.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.K=function(a,b){a=b+this.i;if(0<=a&&a<this.h.length)return this.h[a];throw Error("Index out of bounds");};f.la=function(a,b,c){a=b+this.i;return 0<=a&&a<this.h.length?this.h[a]:c};f.sa=function(){return new cc(this.h,this.i)};
f.P=function(){return this.meta};f.X=function(){return this.i+1<this.h.length?new H(this.h,this.i+1,null):null};f.ba=function(){var a=this.h.length-this.i;return 0>a?0:a};f.N=function(){return Sb(this)};f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return Zb(this.h,b,this.h[this.i],this.i+1)};f.Z=function(a,b,c){return Zb(this.h,b,c,this.i)};f.$=function(){return this.h[this.i]};f.da=function(){return this.i+1<this.h.length?new H(this.h,this.i+1,null):Pb};
f.L=function(){return this.i<this.h.length?this:null};f.U=function(a,b){return new H(this.h,this.i,b)};f.S=function(a,b){return S(b,this)};H.prototype[Ka]=function(){return O(this)};function ec(a){return 0<a.length?new H(a,0,null):null}mb._=function(a,b){return a===b};
var fc=function fc(a){switch(arguments.length){case 0:return fc.F();case 1:return fc.c(arguments[0]);case 2:return fc.f(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return fc.B(arguments[0],arguments[1],new H(c.slice(2),0,null))}};fc.F=function(){return hc};fc.c=function(a){return a};fc.f=function(a,b){return null!=a?Sa(a,b):Sa(Pb,b)};fc.B=function(a,b,c){for(;;)if(q(c))a=fc.f(a,b),b=J(c),c=L(c);else return fc.f(a,b)};
fc.H=function(a){var b=J(a),c=L(a);a=J(c);c=L(c);return fc.B(b,a,c)};fc.I=2;function Q(a){if(null!=a)if(null!=a&&(a.m&2||p===a.Db))a=a.ba(null);else if(Ha(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.m&8388608||p===a.Kb))a:{a=F(a);for(var b=0;;){if($b(a)){a=b+Qa(a);break a}a=L(a);b+=1}}else a=Qa(a);else a=0;return a}function ic(a,b){for(var c=null;;){if(null==a)return c;if(0===b)return F(a)?J(a):c;if(ac(a))return z.j(a,b,c);if(F(a))a=L(a),--b;else return c}}
function bc(a,b){if("number"!==typeof b)throw Error("Index argument to nth must be a number");if(null==a)return a;if(null!=a&&(a.m&16||p===a.vb))return a.K(null,b);if(Ha(a)){if(0<=b&&b<a.length)return a[b];throw Error("Index out of bounds");}if("string"===typeof a){if(0<=b&&b<a.length)return a.charAt(b);throw Error("Index out of bounds");}if(null!=a&&(a.m&64||p===a.Qa)){a:for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(F(a)){a=J(a);break a}throw Error("Index out of bounds");}if(ac(a)){a=
z.f(a,b);break a}if(F(a))a=L(a),--b;else throw Error("Index out of bounds");}return a}if(t(Ta,a))return z.f(a,b);throw Error(["nth not supported on this type ",w.c(Ja(null==a?null:a.constructor))].join(""));}
function U(a,b){if("number"!==typeof b)throw Error("Index argument to nth must be a number.");if(null==a)return null;if(null!=a&&(a.m&16||p===a.vb))return a.la(null,b,null);if(Ha(a))return 0<=b&&b<a.length?a[b]:null;if("string"===typeof a)return 0<=b&&b<a.length?a.charAt(b):null;if(null!=a&&(a.m&64||p===a.Qa))return ic(a,b);if(t(Ta,a))return z.j(a,b,null);throw Error(["nth not supported on this type ",w.c(Ja(null==a?null:a.constructor))].join(""));}
var jc=function jc(a){switch(arguments.length){case 2:return jc.f(arguments[0],arguments[1]);case 3:return jc.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",w.c(arguments.length)].join(""));}};jc.f=function(a,b){return null==a?null:null!=a&&(a.m&256||p===a.Gb)?a.T(null,b):Ha(a)?null!=b&&b<a.length?a[b|0]:null:"string"===typeof a?null!=b&&b<a.length?a.charAt(b|0):null:t(Va,a)?Wa.f(a,b):null};
jc.j=function(a,b,c){return null!=a?null!=a&&(a.m&256||p===a.Gb)?a.D(null,b,c):Ha(a)?null!=b&&0<=b&&b<a.length?a[b|0]:c:"string"===typeof a?null!=b&&0<=b&&b<a.length?a.charAt(b|0):c:t(Va,a)?Wa.j(a,b,c):c:c};jc.I=3;var kc=function kc(a){switch(arguments.length){case 3:return kc.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return kc.B(arguments[0],arguments[1],arguments[2],new H(c.slice(3),0,null))}};
kc.j=function(a,b,c){if(null!=a)a=Xa(a,b,c);else{a=[b,c];b=[];for(c=0;;)if(c<a.length){var d=a[c],e=a[c+1],g=lc(b,d);-1===g?(g=b,g.push(d),g.push(e)):b[g+1]=e;c+=2}else break;a=new Ba(null,b.length/2,b,null)}return a};kc.B=function(a,b,c,d){for(;;)if(a=kc.j(a,b,c),q(d))b=J(d),c=J(L(d)),d=L(L(d));else return a};kc.H=function(a){var b=J(a),c=L(a);a=J(c);var d=L(c);c=J(d);d=L(d);return kc.B(b,a,c,d)};kc.I=3;
function mc(a){var b=null!=a;return(b?null!=a?a.m&131072||p===a.Ib||(a.m?0:t(fb,a)):t(fb,a):b)?gb(a):null}function nc(a){return null!=a?a.m&16777216||p===a.oc?!0:a.m?!1:t(qb,a):t(qb,a)}function oc(a){return null==a?!1:null!=a?a.m&1024||p===a.kc?!0:a.m?!1:t(Ya,a):t(Ya,a)}function pc(a){return null!=a?a.m&67108864||p===a.mc?!0:a.m?!1:t(sb,a):t(sb,a)}function qc(a){return null!=a?a.m&16384||p===a.pc?!0:a.m?!1:t(db,a):t(db,a)}function rc(a){return null!=a?a.A&512||p===a.cc?!0:!1:!1}
function sc(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,--e,b+=1}var tc={};function uc(a){return null==a?!1:!1===a?!1:!0}function vc(a,b){return jc.j(a,b,tc)===tc?!1:!0}function wc(a,b){return(b=F(b))?Na(a,J(b),L(b)):a.F?a.F():a()}function xc(a,b,c){for(c=F(c);;)if(c){var d=J(c);b=a.f?a.f(b,d):a(b,d);if(Xb(b))return eb(b);c=L(c)}else return b}function yc(a,b,c){for(a=Db(a);;)if(a.ea()){var d=a.next();c=b.f?b.f(c,d):b(c,d);if(Xb(c))return eb(c)}else return c}
function Na(a,b,c){return a=null!=c&&(c.m&524288||p===c.nc)?c.Z(null,a,b):Ha(c)?Yb(c,a,b):"string"===typeof c?Yb(c,a,b):t(ib,c)?jb.j(c,a,b):(null!=c?c.A&131072||p===c.hc||(c.A?0:t(Cb,c)):t(Cb,c))?yc(c,a,b):xc(a,b,c)}function zc(a,b){return null!=b?lb(b,a,!0):!0}function Ac(a){return a}function Bc(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}function Cc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
var w=function w(a){switch(arguments.length){case 0:return w.F();case 1:return w.c(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return w.B(arguments[0],new H(c.slice(1),0,null))}};w.F=function(){return""};w.c=function(a){return null==a?"":""+a};w.B=function(a,b){for(a=new sa(""+w.c(a));;)if(q(b))a=a.append(""+w.c(J(b))),b=L(b);else return a.toString()};w.H=function(a){var b=J(a);a=L(a);return w.B(b,a)};w.I=1;
function dc(a,b){if(nc(b))if($b(a)&&$b(b)&&Q(a)!==Q(b))a=!1;else a:for(a=F(a),b=F(b);;){if(null==a){a=null==b;break a}if(null!=b&&N.f(J(a),J(b)))a=L(a),b=L(b);else{a=!1;break a}}else a=null;return uc(a)}function Dc(a,b,c,d,e){this.meta=a;this.first=b;this.ua=c;this.count=d;this.o=e;this.m=65937646;this.A=8192}f=Dc.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};
f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,this.count)}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.meta};f.X=function(){return 1===this.count?null:this.ua};f.ba=function(){return this.count};f.Ra=function(){return this.first};f.Sa=function(){return this.da(null)};
f.N=function(){var a=this.o;return null!=a?a:this.o=a=Sb(this)};f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return wc(b,this)};f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){return this.first};f.da=function(){return 1===this.count?Pb:this.ua};f.L=function(){return this};f.U=function(a,b){return new Dc(b,this.first,this.ua,this.count,this.o)};f.S=function(a,b){return new Dc(this.meta,b,this,this.count+1,null)};Dc.prototype[Ka]=function(){return O(this)};
function Ec(a){this.meta=a;this.m=65937614;this.A=8192}f=Ec.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.meta};f.X=function(){return null};f.ba=function(){return 0};f.Ra=function(){return null};f.Sa=function(){throw Error("Can't pop empty list");};f.N=function(){return Tb};
f.v=function(a,b){return(null!=b?b.m&33554432||p===b.jc||(b.m?0:t(rb,b)):t(rb,b))||nc(b)?null==F(b):!1};f.ca=function(a,b){return wc(b,this)};f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){return null};f.da=function(){return Pb};f.L=function(){return null};f.U=function(a,b){return new Ec(b)};f.S=function(a,b){return new Dc(this.meta,b,null,1,null)};var Pb=new Ec(null);Ec.prototype[Ka]=function(){return O(this)};
function Fc(a,b,c,d){this.meta=a;this.first=b;this.ua=c;this.o=d;this.m=65929452;this.A=8192}f=Fc.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.meta};f.X=function(){return null==this.ua?null:F(this.ua)};f.N=function(){var a=this.o;return null!=a?a:this.o=a=Sb(this)};f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return wc(b,this)};
f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){return this.first};f.da=function(){return null==this.ua?Pb:this.ua};f.L=function(){return this};f.U=function(a,b){return new Fc(b,this.first,this.ua,this.o)};f.S=function(a,b){return new Fc(null,b,this,null)};Fc.prototype[Ka]=function(){return O(this)};function S(a,b){return null==b||null!=b&&(b.m&64||p===b.Qa)?new Fc(null,a,b,null):new Fc(null,a,F(b),null)}
function V(a,b,c,d){this.Xb=a;this.name=b;this.xa=c;this.sb=d;this.m=2153775105;this.A=4096}f=V.prototype;f.toString=function(){return[":",w.c(this.xa)].join("")};f.equiv=function(a){return this.v(null,a)};f.v=function(a,b){return b instanceof V?this.xa===b.xa:!1};
f.call=function(){var a=null;a=function(a,c,d){switch(arguments.length){case 2:return jc.f(c,this);case 3:return jc.j(c,this,d)}throw Error("Invalid arity: "+(arguments.length-1));};a.f=function(a,c){return jc.f(c,this)};a.j=function(a,c,d){return jc.j(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(La(b)))};f.c=function(a){return jc.f(a,this)};f.f=function(a,b){return jc.j(a,this,b)};
f.N=function(){var a=this.sb;if(null!=a)return a;a=this.name;a:{var b=1;for(var c=0;;)if(b<a.length){var d=b+2;c=Ib(c,Hb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16));b=d}else{b=c;break a}}b=1===(a.length&1)?b^Hb(a.charCodeAt(a.length-1)):b;a=Jb(b,Gb(2,a.length));b=Mb(this.Xb);return this.sb=a=(a^b+2654435769+(a<<6)+(a>>2))+2654435769|0};f.R=function(a,b){return C(b,[":",w.c(this.xa)].join(""))};
var Gc=function Gc(a){switch(arguments.length){case 1:return Gc.c(arguments[0]);case 2:return Gc.f(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",w.c(arguments.length)].join(""));}};Gc.c=function(a){if(a instanceof V)return a;if("string"===typeof a){var b=a.split("/");return 2===b.length?new V(b[0],b[1],a,null):new V(null,b[0],a,null)}return null};
Gc.f=function(a,b){a=a instanceof V?Hc(a):a;b=b instanceof V?Hc(b):b;return new V(a,b,[w.c(q(a)?[w.c(a),"/"].join(""):null),w.c(b)].join(""),null)};Gc.I=2;function Ic(a,b,c,d){this.meta=a;this.Ea=b;this.s=c;this.o=d;this.m=32374988;this.A=1}f=Ic.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};function Jc(a){null!=a.Ea&&(a.s=a.Ea.F?a.Ea.F():a.Ea(),a.Ea=null);return a.s}
f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.meta};f.X=function(){this.L(null);return null==this.s?null:L(this.s)};f.N=function(){var a=this.o;return null!=a?a:this.o=a=Sb(this)};f.v=function(a,b){return dc(this,b)};
f.ca=function(a,b){return wc(b,this)};f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){this.L(null);return null==this.s?null:J(this.s)};f.da=function(){this.L(null);return null!=this.s?Ob(this.s):Pb};f.L=function(){Jc(this);if(null==this.s)return null;for(var a=this.s;;)if(a instanceof Ic)a=Jc(a);else return this.s=a,F(this.s)};f.U=function(a,b){return new Ic(b,this.Ea,this.s,this.o)};f.S=function(a,b){return S(b,this)};Ic.prototype[Ka]=function(){return O(this)};
function Kc(a,b){this.Wa=a;this.end=b;this.m=2;this.A=0}Kc.prototype.add=function(a){this.Wa[this.end]=a;return this.end+=1};Kc.prototype.qa=function(){var a=new Lc(this.Wa,0,this.end);this.Wa=null;return a};Kc.prototype.ba=function(){return this.end};function Lc(a,b,c){this.h=a;this.O=b;this.end=c;this.m=524306;this.A=0}f=Lc.prototype;f.ba=function(){return this.end-this.O};f.K=function(a,b){return this.h[this.O+b]};f.la=function(a,b,c){return 0<=b&&b<this.end-this.O?this.h[this.O+b]:c};
f.tb=function(){if(this.O===this.end)throw Error("-drop-first of empty chunk");return new Lc(this.h,this.O+1,this.end)};f.ca=function(a,b){return Zb(this.h,b,this.h[this.O],this.O+1)};f.Z=function(a,b,c){return Zb(this.h,b,c,this.O)};function Mc(a,b,c,d){this.qa=a;this.ra=b;this.meta=c;this.o=d;this.m=31850732;this.A=1536}f=Mc.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};
f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.meta};f.X=function(){if(1<Qa(this.qa))return new Mc(yb(this.qa),this.ra,this.meta,null);var a=pb(this.ra);return null==a?null:a};f.N=function(){var a=this.o;return null!=a?a:this.o=a=Sb(this)};
f.v=function(a,b){return dc(this,b)};f.$=function(){return z.f(this.qa,0)};f.da=function(){return 1<Qa(this.qa)?new Mc(yb(this.qa),this.ra,this.meta,null):null==this.ra?Pb:this.ra};f.L=function(){return this};f.Xa=function(){return this.qa};f.Na=function(){return null==this.ra?Pb:this.ra};f.U=function(a,b){return new Mc(this.qa,this.ra,b,this.o)};f.S=function(a,b){return S(b,this)};f.ub=function(){return null==this.ra?null:this.ra};Mc.prototype[Ka]=function(){return O(this)};
function Nc(a,b){return 0===Qa(a)?b:new Mc(a,b,null,null)}function Oc(a,b){a.add(b)}function Pc(a,b){if($b(b))return Q(b);var c=0;for(b=F(b);;)if(null!=b&&c<a)c+=1,b=L(b);else return c}var Qc=function Qc(a){switch(arguments.length){case 0:return Qc.F();case 1:return Qc.c(arguments[0]);case 2:return Qc.f(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Qc.B(arguments[0],arguments[1],new H(c.slice(2),0,null))}};Qc.F=function(){return ub(hc)};
Qc.c=function(a){return a};Qc.f=function(a,b){return vb(a,b)};Qc.B=function(a,b,c){for(;;)if(a=vb(a,b),q(c))b=J(c),c=L(c);else return a};Qc.H=function(a){var b=J(a),c=L(a);a=J(c);c=L(c);return Qc.B(b,a,c)};Qc.I=2;
function Rc(a,b,c){var d=F(c);if(0===b)return a.F?a.F():a();c=A(d);var e=B(d);if(1===b)return a.c?a.c(c):a(c);d=A(e);var g=B(e);if(2===b)return a.f?a.f(c,d):a(c,d);e=A(g);var h=B(g);if(3===b)return a.j?a.j(c,d,e):a(c,d,e);g=A(h);var k=B(h);if(4===b)return a.G?a.G(c,d,e,g):a(c,d,e,g);h=A(k);var l=B(k);if(5===b)return a.ha?a.ha(c,d,e,g,h):a(c,d,e,g,h);k=A(l);var n=B(l);if(6===b)return a.kb?a.kb(c,d,e,g,h,k):a(c,d,e,g,h,k);l=A(n);var r=B(n);if(7===b)return a.lb?a.lb(c,d,e,g,h,k,l):a(c,d,e,g,h,k,l);n=
A(r);var v=B(r);if(8===b)return a.mb?a.mb(c,d,e,g,h,k,l,n):a(c,d,e,g,h,k,l,n);r=A(v);var y=B(v);if(9===b)return a.nb?a.nb(c,d,e,g,h,k,l,n,r):a(c,d,e,g,h,k,l,n,r);v=A(y);var D=B(y);if(10===b)return a.Za?a.Za(c,d,e,g,h,k,l,n,r,v):a(c,d,e,g,h,k,l,n,r,v);y=A(D);var G=B(D);if(11===b)return a.$a?a.$a(c,d,e,g,h,k,l,n,r,v,y):a(c,d,e,g,h,k,l,n,r,v,y);D=A(G);var I=B(G);if(12===b)return a.ab?a.ab(c,d,e,g,h,k,l,n,r,v,y,D):a(c,d,e,g,h,k,l,n,r,v,y,D);G=A(I);var K=B(I);if(13===b)return a.bb?a.bb(c,d,e,g,h,k,l,n,
r,v,y,D,G):a(c,d,e,g,h,k,l,n,r,v,y,D,G);I=A(K);var M=B(K);if(14===b)return a.cb?a.cb(c,d,e,g,h,k,l,n,r,v,y,D,G,I):a(c,d,e,g,h,k,l,n,r,v,y,D,G,I);K=A(M);var T=B(M);if(15===b)return a.eb?a.eb(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K):a(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K);M=A(T);var Y=B(T);if(16===b)return a.fb?a.fb(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M):a(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M);T=A(Y);var ja=B(Y);if(17===b)return a.gb?a.gb(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M,T):a(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M,T);Y=A(ja);var xa=B(ja);
if(18===b)return a.hb?a.hb(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M,T,Y):a(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M,T,Y);ja=A(xa);xa=B(xa);if(19===b)return a.ib?a.ib(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M,T,Y,ja):a(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M,T,Y,ja);var Pd=A(xa);B(xa);if(20===b)return a.jb?a.jb(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M,T,Y,ja,Pd):a(c,d,e,g,h,k,l,n,r,v,y,D,G,I,K,M,T,Y,ja,Pd);throw Error("Only up to 20 arguments supported on functions");}
function Sc(a,b,c){return null==c?a.c?a.c(b):a.call(a,b):Tc(a,b,A(c),L(c))}function Tc(a,b,c,d){return null==d?a.f?a.f(b,c):a.call(a,b,c):Uc(a,b,c,A(d),L(d))}function Uc(a,b,c,d,e){return null==e?a.j?a.j(b,c,d):a.call(a,b,c,d):Vc(a,b,c,d,A(e),L(e))}
function Vc(a,b,c,d,e,g){if(null==g)return a.G?a.G(b,c,d,e):a.call(a,b,c,d,e);var h=A(g),k=L(g);if(null==k)return a.ha?a.ha(b,c,d,e,h):a.call(a,b,c,d,e,h);g=A(k);var l=L(k);if(null==l)return a.kb?a.kb(b,c,d,e,h,g):a.call(a,b,c,d,e,h,g);k=A(l);var n=L(l);if(null==n)return a.lb?a.lb(b,c,d,e,h,g,k):a.call(a,b,c,d,e,h,g,k);l=A(n);var r=L(n);if(null==r)return a.mb?a.mb(b,c,d,e,h,g,k,l):a.call(a,b,c,d,e,h,g,k,l);n=A(r);var v=L(r);if(null==v)return a.nb?a.nb(b,c,d,e,h,g,k,l,n):a.call(a,b,c,d,e,h,g,k,l,n);
r=A(v);var y=L(v);if(null==y)return a.Za?a.Za(b,c,d,e,h,g,k,l,n,r):a.call(a,b,c,d,e,h,g,k,l,n,r);v=A(y);var D=L(y);if(null==D)return a.$a?a.$a(b,c,d,e,h,g,k,l,n,r,v):a.call(a,b,c,d,e,h,g,k,l,n,r,v);y=A(D);var G=L(D);if(null==G)return a.ab?a.ab(b,c,d,e,h,g,k,l,n,r,v,y):a.call(a,b,c,d,e,h,g,k,l,n,r,v,y);D=A(G);var I=L(G);if(null==I)return a.bb?a.bb(b,c,d,e,h,g,k,l,n,r,v,y,D):a.call(a,b,c,d,e,h,g,k,l,n,r,v,y,D);G=A(I);var K=L(I);if(null==K)return a.cb?a.cb(b,c,d,e,h,g,k,l,n,r,v,y,D,G):a.call(a,b,c,d,
e,h,g,k,l,n,r,v,y,D,G);I=A(K);var M=L(K);if(null==M)return a.eb?a.eb(b,c,d,e,h,g,k,l,n,r,v,y,D,G,I):a.call(a,b,c,d,e,h,g,k,l,n,r,v,y,D,G,I);K=A(M);var T=L(M);if(null==T)return a.fb?a.fb(b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K):a.call(a,b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K);M=A(T);var Y=L(T);if(null==Y)return a.gb?a.gb(b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K,M):a.call(a,b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K,M);T=A(Y);var ja=L(Y);if(null==ja)return a.hb?a.hb(b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K,M,T):a.call(a,b,c,d,e,h,g,k,l,n,r,v,
y,D,G,I,K,M,T);Y=A(ja);var xa=L(ja);if(null==xa)return a.ib?a.ib(b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K,M,T,Y):a.call(a,b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K,M,T,Y);ja=A(xa);xa=L(xa);if(null==xa)return a.jb?a.jb(b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K,M,T,Y,ja):a.call(a,b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K,M,T,Y,ja);b=[b,c,d,e,h,g,k,l,n,r,v,y,D,G,I,K,M,T,Y,ja];for(c=xa;;)if(c)b.push(A(c)),c=L(c);else break;return a.apply(a,b)}
function Wc(a,b){if(a.H){var c=a.I,d=Pc(c+1,b);return d<=c?Rc(a,d,b):a.H(b)}b=F(b);return null==b?a.F?a.F():a.call(a):Sc(a,A(b),L(b))}
function Xc(){"undefined"===typeof ua&&(ua=function(a){this.Vb=a;this.m=393216;this.A=0},ua.prototype.U=function(a,b){return new ua(b)},ua.prototype.P=function(){return this.Vb},ua.prototype.ea=function(){return!1},ua.prototype.next=function(){return Error("No such element")},ua.prototype.remove=function(){return Error("Unsupported operation")},ua.rc=function(){return new W(null,1,5,Yc,[ta.qc],null)},ua.zb=!0,ua.Ua="cljs.core/t_cljs$core17337",ua.Qb=function(a){return C(a,"cljs.core/t_cljs$core17337")});
return new ua(Zc)}function $c(a,b){for(;;){if(null==F(b))return!0;var c=J(b);c=a.c?a.c(c):a(c);if(q(c))b=L(b);else return!1}}
function ad(a){return function(){function b(b,c){return Ia(a.f?a.f(b,c):a(b,c))}function c(b){return Ia(a.c?a.c(b):a(b))}function d(){return Ia(a.F?a.F():a())}var e=null,g=function(){function b(a,b,d){var e=null;if(2<arguments.length){e=0;for(var g=Array(arguments.length-2);e<g.length;)g[e]=arguments[e+2],++e;e=new H(g,0,null)}return c.call(this,a,b,e)}function c(b,c,d){a.H?(b=S(b,S(c,d)),c=a.I,d=2+Pc(c-1,d),d=d<=c?Rc(a,d,b):a.H(b)):d=Tc(a,b,c,F(d));return Ia(d)}b.I=2;b.H=function(a){var b=J(a);a=
L(a);var d=J(a);a=Ob(a);return c(b,d,a)};b.B=c;return b}();e=function(a,e,l){switch(arguments.length){case 0:return d.call(this);case 1:return c.call(this,a);case 2:return b.call(this,a,e);default:var h=null;if(2<arguments.length){h=0;for(var k=Array(arguments.length-2);h<k.length;)k[h]=arguments[h+2],++h;h=new H(k,0,null)}return g.B(a,e,h)}throw Error("Invalid arity: "+(arguments.length-1));};e.I=2;e.H=g.H;e.F=d;e.c=c;e.f=b;e.B=g.B;return e}()}
function bd(a,b,c,d){this.state=a;this.meta=b;this.ac=c;this.Va=d;this.A=16386;this.m=6455296}f=bd.prototype;f.equiv=function(a){return this.v(null,a)};f.v=function(a,b){return this===b};f.Ya=function(){return this.state};f.P=function(){return this.meta};
f.xb=function(a,b,c){a=F(this.Va);for(var d=null,e=0,g=0;;)if(g<e){var h=d.K(null,g),k=U(h,0);h=U(h,1);h.G?h.G(k,this,b,c):h(k,this,b,c);g+=1}else if(a=F(a))rc(a)?(d=zb(a),a=Ab(a),k=d,e=Q(d),d=k):(d=J(a),k=U(d,0),h=U(d,1),h.G?h.G(k,this,b,c):h(k,this,b,c),a=L(a),d=null,e=0),g=0;else return null};f.wb=function(a,b,c){this.Va=kc.j(this.Va,b,c);return this};f.N=function(){return this[aa]||(this[aa]=++ba)};
function cd(a,b){if(a instanceof bd){var c=a.ac;if(null!=c&&!q(c.c?c.c(b):c(b)))throw Error("Validator rejected reference state");c=a.state;a.state=b;null!=a.Va&&tb(a,c,b);return b}return Bb(a,b)}
var dd=function dd(a){switch(arguments.length){case 2:return dd.f(arguments[0],arguments[1]);case 3:return dd.j(arguments[0],arguments[1],arguments[2]);case 4:return dd.G(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return dd.B(arguments[0],arguments[1],arguments[2],arguments[3],new H(c.slice(4),0,null))}};
dd.f=function(a,b){if(a instanceof bd){var c=a.state;b=b.c?b.c(c):b(c);a=cd(a,b)}else a=E.f(a,b);return a};dd.j=function(a,b,c){if(a instanceof bd){var d=a.state;b=b.f?b.f(d,c):b(d,c);a=cd(a,b)}else a=E.j(a,b,c);return a};dd.G=function(a,b,c,d){if(a instanceof bd){var e=a.state;b=b.j?b.j(e,c,d):b(e,c,d);a=cd(a,b)}else a=E.G(a,b,c,d);return a};
dd.B=function(a,b,c,d,e){if(a instanceof bd){var g=a.state;b.H?(c=S(g,S(c,S(d,e))),d=b.I,e=3+Pc(d-2,e),b=e<=d?Rc(b,e,c):b.H(c)):b=Uc(b,g,c,d,F(e));a=cd(a,b)}else a=E.ha(a,b,c,d,e);return a};dd.H=function(a){var b=J(a),c=L(a);a=J(c);var d=L(c);c=J(d);var e=L(d);d=J(e);e=L(e);return dd.B(b,a,c,d,e)};dd.I=4;
var X=function X(a){switch(arguments.length){case 1:return X.c(arguments[0]);case 2:return X.f(arguments[0],arguments[1]);case 3:return X.j(arguments[0],arguments[1],arguments[2]);case 4:return X.G(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X.B(arguments[0],arguments[1],arguments[2],arguments[3],new H(c.slice(4),0,null))}};
X.c=function(a){return function(b){return function(){function c(c,d){d=a.c?a.c(d):a(d);return b.f?b.f(c,d):b(c,d)}function d(a){return b.c?b.c(a):b(a)}function e(){return b.F?b.F():b()}var g=null,h=function(){function c(a,b,c){var e=null;if(2<arguments.length){e=0;for(var g=Array(arguments.length-2);e<g.length;)g[e]=arguments[e+2],++e;e=new H(g,0,null)}return d.call(this,a,b,e)}function d(c,d,e){if(a.H){d=S(d,e);var g=a.I;e=Pc(g,e)+1;e=e<=g?Rc(a,e,d):a.H(d)}else e=Sc(a,d,F(e));return b.f?b.f(c,e):
b(c,e)}c.I=2;c.H=function(a){var b=J(a);a=L(a);var c=J(a);a=Ob(a);return d(b,c,a)};c.B=d;return c}();g=function(a,b,g){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,a);case 2:return c.call(this,a,b);default:var k=null;if(2<arguments.length){k=0;for(var l=Array(arguments.length-2);k<l.length;)l[k]=arguments[k+2],++k;k=new H(l,0,null)}return h.B(a,b,k)}throw Error("Invalid arity: "+(arguments.length-1));};g.I=2;g.H=h.H;g.F=e;g.c=d;g.f=c;g.B=h.B;return g}()}};
X.f=function(a,b){return new Ic(null,function(){var c=F(b);if(c){if(rc(c)){for(var d=zb(c),e=Q(d),g=new Kc(Array(e),0),h=0;;)if(h<e)Oc(g,function(){var b=z.f(d,h);return a.c?a.c(b):a(b)}()),h+=1;else break;return Nc(g.qa(),X.f(a,Ab(c)))}return S(function(){var b=J(c);return a.c?a.c(b):a(b)}(),X.f(a,Ob(c)))}return null},null,null)};
X.j=function(a,b,c){return new Ic(null,function(){var d=F(b),e=F(c);if(d&&e){var g=S;var h=J(d);var k=J(e);h=a.f?a.f(h,k):a(h,k);d=g(h,X.j(a,Ob(d),Ob(e)))}else d=null;return d},null,null)};X.G=function(a,b,c,d){return new Ic(null,function(){var e=F(b),g=F(c),h=F(d);if(e&&g&&h){var k=S;var l=J(e);var n=J(g),r=J(h);l=a.j?a.j(l,n,r):a(l,n,r);e=k(l,X.G(a,Ob(e),Ob(g),Ob(h)))}else e=null;return e},null,null)};
X.B=function(a,b,c,d,e){var g=function l(a){return new Ic(null,function(){var b=X.f(F,a);return $c(Ac,b)?S(X.f(J,b),l(X.f(Ob,b))):null},null,null)};return X.f(function(){return function(b){return Wc(a,b)}}(g),g(fc.B(e,d,ec([c,b]))))};X.H=function(a){var b=J(a),c=L(a);a=J(c);var d=L(c);c=J(d);var e=L(d);d=J(e);e=L(e);return X.B(b,a,c,d,e)};X.I=4;
function ed(){var a=da();return new Ic(null,function(b){return function(){return b(2,a)}}(function(a,c){for(;;)if(c=F(c),0<a&&c)--a,c=Ob(c);else return c}),null,null)}function fd(a,b){return new Ic(null,function(){var c=F(b);if(c){if(rc(c)){for(var d=zb(c),e=Q(d),g=new Kc(Array(e),0),h=0;;)if(h<e){var k=z.f(d,h);k=a.c?a.c(k):a(k);q(k)&&(k=z.f(d,h),g.add(k));h+=1}else break;return Nc(g.qa(),fd(a,Ab(c)))}d=J(c);c=Ob(c);return q(a.c?a.c(d):a(d))?S(d,fd(a,c)):fd(a,c)}return null},null,null)}
function gd(a,b){this.C=a;this.h=b}function hd(a){return new gd(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function id(a){return new gd(a.C,La(a.h))}function jd(a){a=a.l;return 32>a?0:a-1>>>5<<5}function kd(a,b,c){for(;;){if(0===b)return c;var d=hd(a);d.h[0]=c;c=d;b-=5}}
var ld=function ld(a,b,c,d){var g=id(c),h=a.l-1>>>b&31;5===b?g.h[h]=d:(c=c.h[h],null!=c?(b-=5,a=ld.G?ld.G(a,b,c,d):ld(a,b,c,d)):a=kd(null,b-5,d),g.h[h]=a);return g};function md(a,b){throw Error(["No item ",w.c(a)," in vector of length ",w.c(b)].join(""));}function nd(a,b){if(b>=jd(a))return a.W;var c=a.root;for(a=a.shift;;)if(0<a){var d=a-5;c=c.h[b>>>a&31];a=d}else return c.h}
var od=function od(a,b,c,d,e){var h=id(c);if(0===b)h.h[d&31]=e;else{var k=d>>>b&31;b-=5;c=c.h[k];a=od.ha?od.ha(a,b,c,d,e):od(a,b,c,d,e);h.h[k]=a}return h},pd=function pd(a,b,c){var e=a.l-2>>>b&31;if(5<b){b-=5;var g=c.h[e];a=pd.j?pd.j(a,b,g):pd(a,b,g);if(null==a&&0===e)return null;c=id(c);c.h[e]=a;return c}if(0===e)return null;c=id(c);c.h[e]=null;return c};function qd(a,b,c,d,e,g){this.i=a;this.base=b;this.h=c;this.$b=d;this.start=e;this.end=g}qd.prototype.ea=function(){return this.i<this.end};
qd.prototype.next=function(){32===this.i-this.base&&(this.h=nd(this.$b,this.i),this.base+=32);var a=this.h[this.i&31];this.i+=1;return a};function rd(a,b,c,d){return c<d?sd(a,b,bc(a,c),c+1,d):b.F?b.F():b()}function sd(a,b,c,d,e){var g=c;c=d;for(d=nd(a,d);;)if(c<e){var h=c&31;d=0===h?nd(a,c):d;h=d[h];g=b.f?b.f(g,h):b(g,h);if(Xb(g))return eb(g);c+=1}else return g}function W(a,b,c,d,e,g){this.meta=a;this.l=b;this.shift=c;this.root=d;this.W=e;this.o=g;this.m=167668511;this.A=139268}f=W.prototype;
f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.T=function(a,b){return this.D(null,b,null)};f.D=function(a,b,c){return"number"===typeof b?this.la(null,b,c):c};
f.Oa=function(a,b,c){a=0;for(var d=c;;)if(a<this.l){var e=nd(this,a);c=e.length;a:for(var g=0;;)if(g<c){var h=g+a,k=e[g];d=b.j?b.j(d,h,k):b(d,h,k);if(Xb(d)){e=d;break a}g+=1}else{e=d;break a}if(Xb(e))return eb(e);a+=c;d=e}else return d};f.K=function(a,b){return(0<=b&&b<this.l?nd(this,b):md(b,this.l))[b&31]};f.la=function(a,b,c){return 0<=b&&b<this.l?nd(this,b)[b&31]:c};
f.Pb=function(a,b){if(0<=a&&a<this.l){if(jd(this)<=a){var c=La(this.W);c[a&31]=b;return new W(this.meta,this.l,this.shift,this.root,c,null)}return new W(this.meta,this.l,this.shift,od(this,this.shift,this.root,a,b),this.W,null)}if(a===this.l)return this.S(null,b);throw Error(["Index ",w.c(a)," out of bounds  [0,",w.c(this.l),"]"].join(""));};f.sa=function(){var a=this.l;return new qd(0,0,0<Q(this)?nd(this,0):null,this,0,a)};f.P=function(){return this.meta};f.ba=function(){return this.l};
f.ob=function(){return this.K(null,0)};f.pb=function(){return this.K(null,1)};f.Ra=function(){return 0<this.l?this.K(null,this.l-1):null};
f.Sa=function(){if(0===this.l)throw Error("Can't pop empty vector");if(1===this.l)return hb(hc,this.meta);if(1<this.l-jd(this))return new W(this.meta,this.l-1,this.shift,this.root,this.W.slice(0,-1),null);var a=nd(this,this.l-2),b=pd(this,this.shift,this.root);b=null==b?Yc:b;var c=this.l-1;return 5<this.shift&&null==b.h[1]?new W(this.meta,c,this.shift-5,b.h[0],a,null):new W(this.meta,c,this.shift,b,a,null)};f.N=function(){var a=this.o;return null!=a?a:this.o=a=Sb(this)};
f.v=function(a,b){if(b instanceof W)if(this.l===Q(b))for(a=this.sa(null),b=Db(b);;)if(a.ea()){var c=a.next(),d=b.next();if(!N.f(c,d))return!1}else return!0;else return!1;else return dc(this,b)};f.Ha=function(){var a=this.l,b=this.shift,c=new gd({},La(this.root.h)),d=this.W,e=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];sc(d,0,e,0,d.length);return new td(a,b,c,e)};
f.ca=function(a,b){return rd(this,b,0,this.l)};f.Z=function(a,b,c){a=0;for(var d=c;;)if(a<this.l){var e=nd(this,a);c=e.length;a:for(var g=0;;)if(g<c){var h=e[g];d=b.f?b.f(d,h):b(d,h);if(Xb(d)){e=d;break a}g+=1}else{e=d;break a}if(Xb(e))return eb(e);a+=c;d=e}else return d};f.va=function(a,b,c){if("number"===typeof b)return this.Pb(b,c);throw Error("Vector's key for assoc must be a number.");};
f.L=function(){if(0===this.l)var a=null;else if(32>=this.l)a=new H(this.W,0,null);else{a:{a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.h[0];else{a=a.h;break a}}a=new ud(this,a,0,0,null,null)}return a};f.U=function(a,b){return new W(b,this.l,this.shift,this.root,this.W,this.o)};
f.S=function(a,b){if(32>this.l-jd(this)){a=this.W.length;for(var c=Array(a+1),d=0;;)if(d<a)c[d]=this.W[d],d+=1;else break;c[a]=b;return new W(this.meta,this.l+1,this.shift,this.root,c,null)}a=(c=this.l>>>5>1<<this.shift)?this.shift+5:this.shift;c?(c=hd(null),c.h[0]=this.root,d=kd(null,this.shift,new gd(null,this.W)),c.h[1]=d):c=ld(this,this.shift,this.root,new gd(null,this.W));return new W(this.meta,this.l+1,a,c,[b],null)};
f.call=function(){var a=null;a=function(a,c,d){switch(arguments.length){case 2:return this.K(null,c);case 3:return this.la(null,c,d)}throw Error("Invalid arity: "+(arguments.length-1));};a.f=function(a,c){return this.K(null,c)};a.j=function(a,c,d){return this.la(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(La(b)))};f.c=function(a){return this.K(null,a)};f.f=function(a,b){return this.la(null,a,b)};
var Yc=new gd(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),hc=new W(null,0,5,Yc,[],Tb);W.prototype[Ka]=function(){return O(this)};function vd(a){if(Ha(a))a:{var b=a.length;if(32>b)a=new W(null,b,5,Yc,a,null);else for(var c=32,d=(new W(null,32,5,Yc,a.slice(0,32),null)).Ha(null);;)if(c<b){var e=c+1;d=Qc.f(d,a[c]);c=e}else{a=wb(d);break a}}else a=wb(Na(vb,ub(hc),a));return a}
function ud(a,b,c,d,e,g){this.ga=a;this.node=b;this.i=c;this.O=d;this.meta=e;this.o=g;this.m=32375020;this.A=1536}f=ud.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.meta};f.X=function(){if(this.O+1<this.node.length){var a=new ud(this.ga,this.node,this.i,this.O+1,null,null);return null==a?null:a}return this.ub(null)};
f.N=function(){var a=this.o;return null!=a?a:this.o=a=Sb(this)};f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return rd(this.ga,b,this.i+this.O,Q(this.ga))};f.Z=function(a,b,c){return sd(this.ga,b,c,this.i+this.O,Q(this.ga))};f.$=function(){return this.node[this.O]};f.da=function(){if(this.O+1<this.node.length){var a=new ud(this.ga,this.node,this.i,this.O+1,null,null);return null==a?Pb:a}return this.Na(null)};f.L=function(){return this};
f.Xa=function(){var a=this.node;return new Lc(a,this.O,a.length)};f.Na=function(){var a=this.i+this.node.length;return a<Qa(this.ga)?new ud(this.ga,nd(this.ga,a),a,0,null,null):Pb};f.U=function(a,b){return new ud(this.ga,this.node,this.i,this.O,b,null)};f.S=function(a,b){return S(b,this)};f.ub=function(){var a=this.i+this.node.length;return a<Qa(this.ga)?new ud(this.ga,nd(this.ga,a),a,0,null,null):null};ud.prototype[Ka]=function(){return O(this)};
function wd(a,b){return a===b.C?b:new gd(a,La(b.h))}var xd=function xd(a,b,c,d){c=wd(a.root.C,c);var g=a.l-1>>>b&31;if(5===b)a=d;else{var h=c.h[g];null!=h?(b-=5,a=xd.G?xd.G(a,b,h,d):xd(a,b,h,d)):a=kd(a.root.C,b-5,d)}c.h[g]=a;return c};function td(a,b,c,d){this.l=a;this.shift=b;this.root=c;this.W=d;this.A=88;this.m=275}f=td.prototype;
f.Ia=function(a,b){if(this.root.C){if(32>this.l-jd(this))this.W[this.l&31]=b;else{a=new gd(this.root.C,this.W);var c=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];c[0]=b;this.W=c;this.l>>>5>1<<this.shift?(b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],c=this.shift+5,b[0]=
this.root,b[1]=kd(this.root.C,this.shift,a),this.root=new gd(this.root.C,b),this.shift=c):this.root=xd(this,this.shift,this.root,a)}this.l+=1;return this}throw Error("conj! after persistent!");};f.Ta=function(){if(this.root.C){this.root.C=null;var a=this.l-jd(this),b=Array(a);sc(this.W,0,b,0,a);return new W(null,this.l,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.za=function(a,b,c){if("number"===typeof b)return yd(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
function yd(a,b,c){if(a.root.C){if(0<=b&&b<a.l){if(jd(a)<=b)a.W[b&31]=c;else{var d=function(){return function(){return function k(d,h){h=wd(a.root.C,h);if(0===d)h.h[b&31]=c;else{var g=b>>>d&31;d=k(d-5,h.h[g]);h.h[g]=d}return h}}(a)(a.shift,a.root)}();a.root=d}return a}if(b===a.l)return a.Ia(null,c);throw Error(["Index ",w.c(b)," out of bounds for TransientVector of length",w.c(a.l)].join(""));}throw Error("assoc! after persistent!");}
f.ba=function(){if(this.root.C)return this.l;throw Error("count after persistent!");};f.K=function(a,b){if(this.root.C)return(0<=b&&b<this.l?nd(this,b):md(b,this.l))[b&31];throw Error("nth after persistent!");};f.la=function(a,b,c){return 0<=b&&b<this.l?this.K(null,b):c};f.T=function(a,b){return this.D(null,b,null)};f.D=function(a,b,c){return"number"===typeof b?this.la(null,b,c):c};
f.call=function(){var a=null;a=function(a,c,d){switch(arguments.length){case 2:return this.T(null,c);case 3:return this.D(null,c,d)}throw Error("Invalid arity: "+(arguments.length-1));};a.f=function(a,c){return this.T(null,c)};a.j=function(a,c,d){return this.D(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(La(b)))};f.c=function(a){return this.T(null,a)};f.f=function(a,b){return this.D(null,a,b)};function zd(){this.m=2097152;this.A=0}
zd.prototype.equiv=function(a){return this.v(null,a)};zd.prototype.v=function(){return!1};var Ad=new zd;function Bd(a,b){return uc(oc(b)&&!pc(b)?Q(a)===Q(b)?(null!=a?a.m&1048576||p===a.ic||(a.m?0:t(kb,a)):t(kb,a))?zc(function(a,d,e){return N.f(jc.j(b,d,Ad),e)?!0:new Wb(!1)},a):$c(function(a){return N.f(jc.j(b,J(a),Ad),J(L(a)))},a):null:null)}function Cd(a){this.s=a}
Cd.prototype.next=function(){if(null!=this.s){var a=J(this.s),b=U(a,0);a=U(a,1);this.s=L(this.s);return{value:[b,a],done:!1}}return{value:null,done:!0}};
function lc(a,b){if(b instanceof V)a:{var c=a.length;b=b.xa;for(var d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof V&&b===a[d].xa){a=d;break a}d+=2}}else if("string"==typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){a=-1;break a}if(b===a[d]){a=d;break a}d+=2}else if(null==b)a:for(b=a.length,c=0;;){if(b<=c){a=-1;break a}if(null==a[c]){a=c;break a}c+=2}else a:for(c=a.length,d=0;;){if(c<=d){a=-1;break a}if(N.f(b,a[d])){a=d;break a}d+=2}return a}
function Dd(a,b,c){this.h=a;this.i=b;this.ka=c;this.m=32374990;this.A=0}f=Dd.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.ka};f.X=function(){return this.i<this.h.length-2?new Dd(this.h,this.i+2,this.ka):null};f.ba=function(){return(this.h.length-this.i)/2};f.N=function(){return Sb(this)};
f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return wc(b,this)};f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){return new W(null,2,5,Yc,[this.h[this.i],this.h[this.i+1]],null)};f.da=function(){return this.i<this.h.length-2?new Dd(this.h,this.i+2,this.ka):Pb};f.L=function(){return this};f.U=function(a,b){return new Dd(this.h,this.i,b)};f.S=function(a,b){return S(b,this)};Dd.prototype[Ka]=function(){return O(this)};function Ed(a,b,c){this.h=a;this.i=b;this.l=c}
Ed.prototype.ea=function(){return this.i<this.l};Ed.prototype.next=function(){var a=new W(null,2,5,Yc,[this.h[this.i],this.h[this.i+1]],null);this.i+=2;return a};function Ba(a,b,c,d){this.meta=a;this.l=b;this.h=c;this.o=d;this.m=16647951;this.A=139268}f=Ba.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.keys=function(){return O(Fd(this))};f.entries=function(){return new Cd(F(F(this)))};f.values=function(){return O(Gd(this))};
f.has=function(a){return vc(this,a)};f.get=function(a,b){return this.D(null,a,b)};f.forEach=function(a){for(var b=F(this),c=null,d=0,e=0;;)if(e<d){var g=c.K(null,e),h=U(g,0);g=U(g,1);a.f?a.f(g,h):a(g,h);e+=1}else if(b=F(b))rc(b)?(c=zb(b),b=Ab(b),h=c,d=Q(c),c=h):(c=J(b),h=U(c,0),g=U(c,1),a.f?a.f(g,h):a(g,h),b=L(b),c=null,d=0),e=0;else return null};f.T=function(a,b){return this.D(null,b,null)};f.D=function(a,b,c){a=lc(this.h,b);return-1===a?c:this.h[a+1]};
f.Oa=function(a,b,c){a=this.h.length;for(var d=0;;)if(d<a){var e=this.h[d],g=this.h[d+1];c=b.j?b.j(c,e,g):b(c,e,g);if(Xb(c))return eb(c);d+=2}else return c};f.sa=function(){return new Ed(this.h,0,2*this.l)};f.P=function(){return this.meta};f.ba=function(){return this.l};f.N=function(){var a=this.o;return null!=a?a:this.o=a=Ub(this)};
f.v=function(a,b){if(oc(b)&&!pc(b))if(a=this.h.length,this.l===b.ba(null))for(var c=0;;)if(c<a){var d=b.D(null,this.h[c],tc);if(d!==tc)if(N.f(this.h[c+1],d))c+=2;else return!1;else return!1}else return!0;else return!1;else return!1};f.Ha=function(){return new Hd({},this.h.length,La(this.h))};f.ca=function(a,b){a:if(a=Db(this),q(a.ea()))for(var c=a.next();;)if(a.ea()){var d=a.next();c=b.f?b.f(c,d):b(c,d);if(Xb(c)){b=eb(c);break a}}else{b=c;break a}else b=b.F?b.F():b();return b};
f.Z=function(a,b,c){return yc(this,b,c)};f.va=function(a,b,c){a=lc(this.h,b);if(-1===a){if(this.l<Id){a=this.h;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new Ba(this.meta,this.l+1,e,null)}a=Jd;a=null!=a?null!=a&&(a.A&4||p===a.ec)?hb(wb(Na(vb,ub(a),this)),mc(a)):Na(Sa,a,this):Na(fc,Pb,this);return hb(Xa(a,b,c),this.meta)}if(c===this.h[a+1])return this;b=La(this.h);b[a+1]=c;return new Ba(this.meta,this.l,b,null)};
f.L=function(){var a=this.h;return 0<=a.length-2?new Dd(a,0,null):null};f.U=function(a,b){return new Ba(b,this.l,this.h,this.o)};f.S=function(a,b){if(qc(b))return this.va(null,z.f(b,0),z.f(b,1));a=this;for(b=F(b);;){if(null==b)return a;var c=J(b);if(qc(c))a=a.va(null,z.f(c,0),z.f(c,1)),b=L(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null;a=function(a,c,d){switch(arguments.length){case 2:return this.T(null,c);case 3:return this.D(null,c,d)}throw Error("Invalid arity: "+(arguments.length-1));};a.f=function(a,c){return this.T(null,c)};a.j=function(a,c,d){return this.D(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(La(b)))};f.c=function(a){return this.T(null,a)};f.f=function(a,b){return this.D(null,a,b)};var Zc=new Ba(null,0,[],Vb),Id=8;Ba.prototype[Ka]=function(){return O(this)};
function Hd(a,b,c){this.Da=a;this.Fa=b;this.h=c;this.m=258;this.A=56}f=Hd.prototype;f.ba=function(){if(q(this.Da))return Bc(this.Fa);throw Error("count after persistent!");};f.T=function(a,b){return this.D(null,b,null)};f.D=function(a,b,c){if(q(this.Da))return a=lc(this.h,b),-1===a?c:this.h[a+1];throw Error("lookup after persistent!");};
f.Ia=function(a,b){if(q(this.Da)){if(null!=b?b.m&2048||p===b.Hb||(b.m?0:t(Za,b)):t(Za,b))return this.za(null,$a(b),ab(b));a=F(b);for(b=this;;){var c=J(a);if(q(c))a=L(a),b=b.za(null,$a(c),ab(c));else return b}}else throw Error("conj! after persistent!");};f.Ta=function(){if(q(this.Da))return this.Da=!1,new Ba(null,Bc(this.Fa),this.h,null);throw Error("persistent! called twice");};
f.za=function(a,b,c){if(q(this.Da)){a=lc(this.h,b);if(-1===a){if(this.Fa+2<=2*Id)return this.Fa+=2,this.h.push(b),this.h.push(c),this;a:{a=this.Fa;for(var d=this.h,e=ub(Jd),g=0;;)if(g<a)e=xb(e,d[g],d[g+1]),g+=2;else break a}return xb(e,b,c)}c!==this.h[a+1]&&(this.h[a+1]=c);return this}throw Error("assoc! after persistent!");};function Kd(){this.ja=!1}function Ld(a,b){return a===b?!0:a===b||a instanceof V&&b instanceof V&&a.xa===b.xa?!0:N.f(a,b)}function Md(a,b,c){a=La(a);a[b]=c;return a}
function Nd(a,b,c,d){a=a.Aa(b);a.h[c]=d;return a}function Od(a,b,c){for(var d=a.length,e=0,g=c;;)if(e<d){c=a[e];if(null!=c){var h=a[e+1];c=b.j?b.j(g,c,h):b(g,c,h)}else c=a[e+1],c=null!=c?c.Ka(b,g):g;if(Xb(c))return c;e+=2;g=c}else return g}function Qd(a,b,c,d){this.h=a;this.i=b;this.La=c;this.oa=d}
Qd.prototype.advance=function(){for(var a=this.h.length;;)if(this.i<a){var b=this.h[this.i],c=this.h[this.i+1];null!=b?b=this.La=new W(null,2,5,Yc,[b,c],null):null!=c?(b=Db(c),b=b.ea()?this.oa=b:!1):b=!1;this.i+=2;if(b)return!0}else return!1};Qd.prototype.ea=function(){var a=null!=this.La;return a?a:(a=null!=this.oa)?a:this.advance()};
Qd.prototype.next=function(){if(null!=this.La){var a=this.La;this.La=null;return a}if(null!=this.oa)return a=this.oa.next(),this.oa.ea()||(this.oa=null),a;if(this.advance())return this.next();throw Error("No such element");};Qd.prototype.remove=function(){return Error("Unsupported operation")};function Rd(a,b,c){this.C=a;this.J=b;this.h=c;this.A=131072;this.m=0}f=Rd.prototype;
f.Aa=function(a){if(a===this.C)return this;var b=Cc(this.J),c=Array(0>b?4:2*(b+1));sc(this.h,0,c,0,2*b);return new Rd(a,this.J,c)};f.Ja=function(){return Sd(this.h,0,null)};f.Ka=function(a,b){return Od(this.h,a,b)};f.Ba=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.J&e))return d;var g=Cc(this.J&e-1);e=this.h[2*g];g=this.h[2*g+1];return null==e?g.Ba(a+5,b,c,d):Ld(c,e)?g:d};
f.na=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=Cc(this.J&h-1);if(0===(this.J&h)){var l=Cc(this.J);if(2*l<this.h.length){a=this.Aa(a);b=a.h;g.ja=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];--l;--c;--g}b[2*k]=d;b[2*k+1]=e;a.J|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Td.na(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==
(this.J>>>d&1)&&(k[d]=null!=this.h[e]?Td.na(a,b+5,Nb(this.h[e]),this.h[e],this.h[e+1],g):this.h[e+1],e+=2),d+=1;else break;return new Ud(a,l+1,k)}b=Array(2*(l+4));sc(this.h,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;sc(this.h,2*k,b,2*(k+1),2*(l-k));g.ja=!0;a=this.Aa(a);a.h=b;a.J|=h;return a}l=this.h[2*k];h=this.h[2*k+1];if(null==l)return l=h.na(a,b+5,c,d,e,g),l===h?this:Nd(this,a,2*k+1,l);if(Ld(d,l))return e===h?this:Nd(this,a,2*k+1,e);g.ja=!0;g=b+5;b=Nb(l);if(b===c)e=new Vd(null,b,2,[l,h,d,e]);else{var n=new Kd;
e=Td.na(a,g,b,l,h,n).na(a,g,c,d,e,n)}d=2*k;k=2*k+1;a=this.Aa(a);a.h[d]=null;a.h[k]=e;return a};
f.ma=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=Cc(this.J&g-1);if(0===(this.J&g)){var k=Cc(this.J);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Td.ma(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.J>>>c&1)&&(h[c]=null!=this.h[d]?Td.ma(a+5,Nb(this.h[d]),this.h[d],this.h[d+1],e):this.h[d+1],d+=2),c+=1;else break;return new Ud(null,k+1,h)}a=Array(2*(k+1));sc(this.h,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;sc(this.h,2*h,a,2*(h+1),2*(k-h));e.ja=!0;return new Rd(null,this.J|g,a)}var l=this.h[2*h];g=this.h[2*h+1];if(null==l)return k=g.ma(a+5,b,c,d,e),k===g?this:new Rd(null,this.J,Md(this.h,2*h+1,k));if(Ld(c,l))return d===g?this:new Rd(null,this.J,Md(this.h,2*h+1,d));e.ja=!0;e=this.J;k=this.h;a+=5;var n=Nb(l);if(n===b)c=new Vd(null,n,2,[l,g,c,d]);else{var r=new Kd;c=Td.ma(a,n,l,g,r).ma(a,b,c,d,r)}a=2*h;h=2*h+1;d=La(k);d[a]=null;d[h]=c;return new Rd(null,e,d)};
f.sa=function(){return new Qd(this.h,0,null,null)};var Td=new Rd(null,0,[]);function Wd(a,b,c){this.h=a;this.i=b;this.oa=c}Wd.prototype.ea=function(){for(var a=this.h.length;;){if(null!=this.oa&&this.oa.ea())return!0;if(this.i<a){var b=this.h[this.i];this.i+=1;null!=b&&(this.oa=Db(b))}else return!1}};Wd.prototype.next=function(){if(this.ea())return this.oa.next();throw Error("No such element");};Wd.prototype.remove=function(){return Error("Unsupported operation")};
function Ud(a,b,c){this.C=a;this.l=b;this.h=c;this.A=131072;this.m=0}f=Ud.prototype;f.Aa=function(a){return a===this.C?this:new Ud(a,this.l,La(this.h))};f.Ja=function(){return Xd(this.h,0,null)};f.Ka=function(a,b){for(var c=this.h.length,d=0;;)if(d<c){var e=this.h[d];if(null!=e&&(b=e.Ka(a,b),Xb(b)))return b;d+=1}else return b};f.Ba=function(a,b,c,d){var e=this.h[b>>>a&31];return null!=e?e.Ba(a+5,b,c,d):d};
f.na=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.h[h];if(null==k)return a=Nd(this,a,h,Td.na(a,b+5,c,d,e,g)),a.l+=1,a;b=k.na(a,b+5,c,d,e,g);return b===k?this:Nd(this,a,h,b)};f.ma=function(a,b,c,d,e){var g=b>>>a&31,h=this.h[g];if(null==h)return new Ud(null,this.l+1,Md(this.h,g,Td.ma(a+5,b,c,d,e)));a=h.ma(a+5,b,c,d,e);return a===h?this:new Ud(null,this.l,Md(this.h,g,a))};f.sa=function(){return new Wd(this.h,0,null)};
function Yd(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Ld(c,a[d]))return d;d+=2}else return-1}function Vd(a,b,c,d){this.C=a;this.wa=b;this.l=c;this.h=d;this.A=131072;this.m=0}f=Vd.prototype;f.Aa=function(a){if(a===this.C)return this;var b=Array(2*(this.l+1));sc(this.h,0,b,0,2*this.l);return new Vd(a,this.wa,this.l,b)};f.Ja=function(){return Sd(this.h,0,null)};f.Ka=function(a,b){return Od(this.h,a,b)};f.Ba=function(a,b,c,d){a=Yd(this.h,this.l,c);return 0>a?d:Ld(c,this.h[a])?this.h[a+1]:d};
f.na=function(a,b,c,d,e,g){if(c===this.wa){b=Yd(this.h,this.l,d);if(-1===b){if(this.h.length>2*this.l)return b=2*this.l,c=2*this.l+1,a=this.Aa(a),a.h[b]=d,a.h[c]=e,g.ja=!0,a.l+=1,a;c=this.h.length;b=Array(c+2);sc(this.h,0,b,0,c);b[c]=d;b[c+1]=e;g.ja=!0;d=this.l+1;a===this.C?(this.h=b,this.l=d,a=this):a=new Vd(this.C,this.wa,d,b);return a}return this.h[b+1]===e?this:Nd(this,a,b+1,e)}return(new Rd(a,1<<(this.wa>>>b&31),[null,this,null,null])).na(a,b,c,d,e,g)};
f.ma=function(a,b,c,d,e){return b===this.wa?(a=Yd(this.h,this.l,c),-1===a?(a=2*this.l,b=Array(a+2),sc(this.h,0,b,0,a),b[a]=c,b[a+1]=d,e.ja=!0,new Vd(null,this.wa,this.l+1,b)):N.f(this.h[a+1],d)?this:new Vd(null,this.wa,this.l,Md(this.h,a+1,d))):(new Rd(null,1<<(this.wa>>>a&31),[null,this])).ma(a,b,c,d,e)};f.sa=function(){return new Qd(this.h,0,null,null)};function Zd(a,b,c,d,e){this.meta=a;this.pa=b;this.i=c;this.s=d;this.o=e;this.m=32374988;this.A=0}f=Zd.prototype;f.toString=function(){return Fb(this)};
f.equiv=function(a){return this.v(null,a)};f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.meta};f.X=function(){return null==this.s?Sd(this.pa,this.i+2,null):Sd(this.pa,this.i,L(this.s))};f.N=function(){var a=this.o;return null!=a?a:this.o=a=Sb(this)};
f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return wc(b,this)};f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){return null==this.s?new W(null,2,5,Yc,[this.pa[this.i],this.pa[this.i+1]],null):J(this.s)};f.da=function(){var a=null==this.s?Sd(this.pa,this.i+2,null):Sd(this.pa,this.i,L(this.s));return null!=a?a:Pb};f.L=function(){return this};f.U=function(a,b){return new Zd(b,this.pa,this.i,this.s,this.o)};f.S=function(a,b){return S(b,this)};Zd.prototype[Ka]=function(){return O(this)};
function Sd(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new Zd(null,a,b,null,null);var d=a[b+1];if(q(d)&&(d=d.Ja(),q(d)))return new Zd(null,a,b+2,d,null);b+=2}else return null;else return new Zd(null,a,b,c,null)}function $d(a,b,c,d,e){this.meta=a;this.pa=b;this.i=c;this.s=d;this.o=e;this.m=32374988;this.A=0}f=$d.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};
f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.meta};f.X=function(){return Xd(this.pa,this.i,L(this.s))};f.N=function(){var a=this.o;return null!=a?a:this.o=a=Sb(this)};f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return wc(b,this)};
f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){return J(this.s)};f.da=function(){var a=Xd(this.pa,this.i,L(this.s));return null!=a?a:Pb};f.L=function(){return this};f.U=function(a,b){return new $d(b,this.pa,this.i,this.s,this.o)};f.S=function(a,b){return S(b,this)};$d.prototype[Ka]=function(){return O(this)};
function Xd(a,b,c){if(null==c)for(c=a.length;;)if(b<c){var d=a[b];if(q(d)&&(d=d.Ja(),q(d)))return new $d(null,a,b+1,d,null);b+=1}else return null;else return new $d(null,a,b,c,null)}function ae(a,b,c){this.V=a;this.Cb=b;this.qb=c}ae.prototype.ea=function(){return!this.qb||this.Cb.ea()};ae.prototype.next=function(){if(this.qb)return this.Cb.next();this.qb=!0;return new W(null,2,5,Yc,[null,this.V],null)};ae.prototype.remove=function(){return Error("Unsupported operation")};
function be(a,b,c,d,e,g){this.meta=a;this.l=b;this.root=c;this.fa=d;this.V=e;this.o=g;this.m=16123663;this.A=139268}f=be.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.keys=function(){return O(Fd(this))};f.entries=function(){return new Cd(F(F(this)))};f.values=function(){return O(Gd(this))};f.has=function(a){return vc(this,a)};f.get=function(a,b){return this.D(null,a,b)};
f.forEach=function(a){for(var b=F(this),c=null,d=0,e=0;;)if(e<d){var g=c.K(null,e),h=U(g,0);g=U(g,1);a.f?a.f(g,h):a(g,h);e+=1}else if(b=F(b))rc(b)?(c=zb(b),b=Ab(b),h=c,d=Q(c),c=h):(c=J(b),h=U(c,0),g=U(c,1),a.f?a.f(g,h):a(g,h),b=L(b),c=null,d=0),e=0;else return null};f.T=function(a,b){return this.D(null,b,null)};f.D=function(a,b,c){return null==b?this.fa?this.V:c:null==this.root?c:this.root.Ba(0,Nb(b),b,c)};
f.Oa=function(a,b,c){a=this.fa?b.j?b.j(c,null,this.V):b(c,null,this.V):c;Xb(a)?b=eb(a):null!=this.root?(b=this.root.Ka(b,a),b=Xb(b)?eb(b):b):b=a;return b};f.sa=function(){var a=this.root?Db(this.root):Xc();return this.fa?new ae(this.V,a,!1):a};f.P=function(){return this.meta};f.ba=function(){return this.l};f.N=function(){var a=this.o;return null!=a?a:this.o=a=Ub(this)};f.v=function(a,b){return Bd(this,b)};f.Ha=function(){return new ce({},this.root,this.l,this.fa,this.V)};
f.va=function(a,b,c){if(null==b)return this.fa&&c===this.V?this:new be(this.meta,this.fa?this.l:this.l+1,this.root,!0,c,null);a=new Kd;b=(null==this.root?Td:this.root).ma(0,Nb(b),b,c,a);return b===this.root?this:new be(this.meta,a.ja?this.l+1:this.l,b,this.fa,this.V,null)};f.L=function(){if(0<this.l){var a=null!=this.root?this.root.Ja():null;return this.fa?S(new W(null,2,5,Yc,[null,this.V],null),a):a}return null};f.U=function(a,b){return new be(b,this.l,this.root,this.fa,this.V,this.o)};
f.S=function(a,b){if(qc(b))return this.va(null,z.f(b,0),z.f(b,1));a=this;for(b=F(b);;){if(null==b)return a;var c=J(b);if(qc(c))a=a.va(null,z.f(c,0),z.f(c,1)),b=L(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null;a=function(a,c,d){switch(arguments.length){case 2:return this.T(null,c);case 3:return this.D(null,c,d)}throw Error("Invalid arity: "+(arguments.length-1));};a.f=function(a,c){return this.T(null,c)};a.j=function(a,c,d){return this.D(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(La(b)))};f.c=function(a){return this.T(null,a)};f.f=function(a,b){return this.D(null,a,b)};var Jd=new be(null,0,null,!1,null,Vb);be.prototype[Ka]=function(){return O(this)};
function ce(a,b,c,d,e){this.C=a;this.root=b;this.count=c;this.fa=d;this.V=e;this.m=258;this.A=56}function de(a,b,c){if(a.C){if(null==b)a.V!==c&&(a.V=c),a.fa||(a.count+=1,a.fa=!0);else{var d=new Kd;b=(null==a.root?Td:a.root).na(a.C,0,Nb(b),b,c,d);b!==a.root&&(a.root=b);d.ja&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=ce.prototype;f.ba=function(){if(this.C)return this.count;throw Error("count after persistent!");};
f.T=function(a,b){return null==b?this.fa?this.V:null:null==this.root?null:this.root.Ba(0,Nb(b),b)};f.D=function(a,b,c){return null==b?this.fa?this.V:c:null==this.root?c:this.root.Ba(0,Nb(b),b,c)};f.Ia=function(a,b){a:if(this.C)if(null!=b?b.m&2048||p===b.Hb||(b.m?0:t(Za,b)):t(Za,b))a=de(this,$a(b),ab(b));else for(a=F(b),b=this;;){var c=J(a);if(q(c))a=L(a),b=de(b,$a(c),ab(c));else{a=b;break a}}else throw Error("conj! after persistent");return a};
f.Ta=function(){if(this.C){this.C=null;var a=new be(null,this.count,this.root,this.fa,this.V,null)}else throw Error("persistent! called twice");return a};f.za=function(a,b,c){return de(this,b,c)};function ee(a,b){this.w=a;this.ka=b;this.m=32374988;this.A=0}f=ee.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};
f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.ka};f.X=function(){var a=(null!=this.w?this.w.m&128||p===this.w.Pa||(this.w.m?0:t(Ua,this.w)):t(Ua,this.w))?this.w.X(null):L(this.w);return null==a?null:new ee(a,this.ka)};f.N=function(){return Sb(this)};
f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return wc(b,this)};f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){return this.w.$(null).ob()};f.da=function(){var a=(null!=this.w?this.w.m&128||p===this.w.Pa||(this.w.m?0:t(Ua,this.w)):t(Ua,this.w))?this.w.X(null):L(this.w);return null!=a?new ee(a,this.ka):Pb};f.L=function(){return this};f.U=function(a,b){return new ee(this.w,b)};f.S=function(a,b){return S(b,this)};ee.prototype[Ka]=function(){return O(this)};
function Fd(a){return(a=F(a))?new ee(a,null):null}function fe(a,b){this.w=a;this.ka=b;this.m=32374988;this.A=0}f=fe.prototype;f.toString=function(){return Fb(this)};f.equiv=function(a){return this.v(null,a)};f.indexOf=function(){var a=null;a=function(a,c){switch(arguments.length){case 1:return P(this,a,0);case 2:return P(this,a,c)}throw Error("Invalid arity: "+(arguments.length-1));};a.c=function(a){return P(this,a,0)};a.f=function(a,c){return P(this,a,c)};return a}();
f.lastIndexOf=function(){function a(a){return R(this,a,Q(this))}var b=null;b=function(b,d){switch(arguments.length){case 1:return a.call(this,b);case 2:return R(this,b,d)}throw Error("Invalid arity: "+(arguments.length-1));};b.c=a;b.f=function(a,b){return R(this,a,b)};return b}();f.P=function(){return this.ka};f.X=function(){var a=(null!=this.w?this.w.m&128||p===this.w.Pa||(this.w.m?0:t(Ua,this.w)):t(Ua,this.w))?this.w.X(null):L(this.w);return null==a?null:new fe(a,this.ka)};f.N=function(){return Sb(this)};
f.v=function(a,b){return dc(this,b)};f.ca=function(a,b){return wc(b,this)};f.Z=function(a,b,c){return xc(b,c,this)};f.$=function(){return this.w.$(null).pb()};f.da=function(){var a=(null!=this.w?this.w.m&128||p===this.w.Pa||(this.w.m?0:t(Ua,this.w)):t(Ua,this.w))?this.w.X(null):L(this.w);return null!=a?new fe(a,this.ka):Pb};f.L=function(){return this};f.U=function(a,b){return new fe(this.w,b)};f.S=function(a,b){return S(b,this)};fe.prototype[Ka]=function(){return O(this)};
function Gd(a){return(a=F(a))?new fe(a,null):null}function Hc(a){if(null!=a&&(a.A&4096||p===a.lc))return a.name;if("string"===typeof a)return a;throw Error(["Doesn't support name: ",w.c(a)].join(""));}
function ge(a,b,c,d,e,g,h){var k=ya;ya=null==ya?null:ya-1;try{if(null!=ya&&0>ya)return C(a,"#");C(a,c);if(0===Ga.c(g))F(h)&&C(a,function(){var a=he.c(g);return q(a)?a:"..."}());else{if(F(h)){var l=J(h);b.j?b.j(l,a,g):b(l,a,g)}for(var n=L(h),r=Ga.c(g)-1;;)if(!n||null!=r&&0===r){F(n)&&0===r&&(C(a,d),C(a,function(){var a=he.c(g);return q(a)?a:"..."}()));break}else{C(a,d);var v=J(n);c=a;h=g;b.j?b.j(v,c,h):b(v,c,h);var y=L(n);c=r-1;n=y;r=c}}return C(a,e)}finally{ya=k}}
function ie(a,b){b=F(b);for(var c=null,d=0,e=0;;)if(e<d){var g=c.K(null,e);C(a,g);e+=1}else if(b=F(b))c=b,rc(c)?(b=zb(c),d=Ab(c),c=b,g=Q(b),b=d,d=g):(g=J(c),C(a,g),b=L(c),c=null,d=0),e=0;else return null}var je={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function ke(a){return[w.c('"'),w.c(a.replace(/[\\"\b\f\n\r\t]/g,function(a){return je[a]})),w.c('"')].join("")}
function le(a,b){return(a=uc(jc.f(a,Ea)))?(a=null!=b?b.m&131072||p===b.Ib?!0:!1:!1)?null!=mc(b):a:a}
function me(a,b,c){if(null==a)return C(b,"nil");le(c,a)&&(C(b,"^"),Z(mc(a),b,c),C(b," "));if(a.zb)return a.Qb(b);if(null!=a&&(a.m&2147483648||p===a.Y))return a.R(null,b,c);if(!0===a||!1===a)return C(b,""+w.c(a));if("number"===typeof a)return C(b,isNaN(a)?"##NaN":a===Number.POSITIVE_INFINITY?"##Inf":a===Number.NEGATIVE_INFINITY?"##-Inf":""+w.c(a));if(null!=a&&a.constructor===Object)return C(b,"#js "),ne(X.f(function(b){var c=Yc;var d=/[A-Za-z_\*\+\?!\-'][\w\*\+\?!\-']*/;if("string"===typeof b)d=d.exec(b),
d=N.f(J(d),b)?1===Q(d)?J(d):vd(d):null;else throw new TypeError("re-matches must match against a string.");return new W(null,2,5,c,[null!=d?Gc.c(b):b,a[b]],null)},ca(a)),b,c);if(Ha(a))return ge(b,Z,"#js ["," ","]",c,a);if("string"==typeof a)return q(Da.c(c))?C(b,ke(a)):C(b,a);if("function"==m(a)){var d=a.name;c=q(function(){var a=null==d;return a?a:/^[\s\xa0]*$/.test(d)}())?"Function":d;return ie(b,ec(["#object[",c,"","]"]))}if(a instanceof Date)return c=function(a,b){for(a=""+w.c(a);;)if(Q(a)<b)a=
["0",w.c(a)].join("");else return a},ie(b,ec(['#inst "',""+w.c(a.getUTCFullYear()),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),3),"-",'00:00"']));if(a instanceof RegExp)return ie(b,ec(['#"',a.source,'"']));if(q(function(){var b=null==a?null:a.constructor;return null==b?null:b.Ua}()))return ie(b,ec(["#object[",a.constructor.Ua.replace(/\//g,"."),"]"]));d=function(){var b=null==a?null:
a.constructor;return null==b?null:b.name}();c=q(function(){var a=null==d;return a?a:/^[\s\xa0]*$/.test(d)}())?"Object":d;return null==a.constructor?ie(b,ec(["#object[",c,"]"])):ie(b,ec(["#object[",c," ",""+w.c(a),"]"]))}function Z(a,b,c){var d=oe.c(c);return q(d)?(c=kc.j(c,pe,me),d.j?d.j(a,b,c):d(a,b,c)):me(a,b,c)}
function qe(a,b){var c=new sa;a:{var d=new Eb(c);Z(J(a),d,b);a=F(L(a));for(var e=null,g=0,h=0;;)if(h<g){var k=e.K(null,h);C(d," ");Z(k,d,b);h+=1}else if(a=F(a))e=a,rc(e)?(a=zb(e),g=Ab(e),e=a,k=Q(a),a=g,g=k):(k=J(e),C(d," "),Z(k,d,b),a=L(e),e=null,g=0),h=0;else break a}return c}function re(a,b,c,d,e){return ge(d,function(a,b,d){var e=$a(a);c.j?c.j(e,b,d):c(e,b,d);C(b," ");a=ab(a);return c.j?c.j(a,b,d):c(a,b,d)},[w.c(a),"{"].join(""),", ","}",e,F(b))}
function ne(a,b,c){var d=Z,e=(oc(a),null),g=U(e,0);e=U(e,1);return q(g)?re(["#:",w.c(g)].join(""),e,d,b,c):re(null,a,d,b,c)}H.prototype.Y=p;H.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};Ic.prototype.Y=p;Ic.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};Zd.prototype.Y=p;Zd.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};Dd.prototype.Y=p;Dd.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};ud.prototype.Y=p;
ud.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};Fc.prototype.Y=p;Fc.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};be.prototype.Y=p;be.prototype.R=function(a,b,c){return ne(this,b,c)};$d.prototype.Y=p;$d.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};Mc.prototype.Y=p;Mc.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};bd.prototype.Y=p;
bd.prototype.R=function(a,b,c){C(b,"#object [cljs.core.Atom ");Z(new Ba(null,1,[se,this.state],null),b,c);return C(b,"]")};fe.prototype.Y=p;fe.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};W.prototype.Y=p;W.prototype.R=function(a,b,c){return ge(b,Z,"["," ","]",c,this)};Ec.prototype.Y=p;Ec.prototype.R=function(a,b){return C(b,"()")};Ba.prototype.Y=p;Ba.prototype.R=function(a,b,c){return ne(this,b,c)};ee.prototype.Y=p;ee.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};
Dc.prototype.Y=p;Dc.prototype.R=function(a,b,c){return ge(b,Z,"("," ",")",c,this)};function te(){}var ue=function ue(a){if(null!=a&&null!=a.Fb)return a.Fb(a);var c=ue[m(null==a?null:a)];if(null!=c)return c.c?c.c(a):c(a);c=ue._;if(null!=c)return c.c?c.c(a):c(a);throw u("IEncodeJS.-clj-\x3ejs",a);};
function ve(a){if(null!=a?p===a.Eb||(a.Rb?0:t(te,a)):t(te,a))a=ue(a);else if("string"===typeof a||"number"===typeof a||a instanceof V)a=we(a);else{a=ec([a]);var b=Aa();a=null==a||Ia(F(a))?"":""+w.c(qe(a,b))}return a}
var we=function we(a){if(null==a)return null;if(null!=a?p===a.Eb||(a.Rb?0:t(te,a)):t(te,a))return ue(a);if(a instanceof V)return Hc(a);if(oc(a)){var c={};a=F(a);for(var d=null,e=0,g=0;;)if(g<e){var h=d.K(null,g),k=U(h,0),l=U(h,1);h=c;k=ve(k);l=we.c?we.c(l):we(l);h[k]=l;g+=1}else if(a=F(a))rc(a)?(e=zb(a),a=Ab(a),d=e,e=Q(e)):(d=J(a),e=U(d,0),g=U(d,1),d=c,e=ve(e),g=we.c?we.c(g):we(g),d[e]=g,a=L(a),d=null,e=0),g=0;else break;return c}if(null==a?0:null!=a?a.m&8||p===a.dc||(a.m?0:t(Ra,a)):t(Ra,a)){c=[];
a=F(X.f(we,a));d=null;for(g=e=0;;)if(g<e)h=d.K(null,g),c.push(h),g+=1;else if(a=F(a))d=a,rc(d)?(a=zb(d),g=Ab(d),d=a,e=Q(a),a=g):(a=J(d),c.push(a),a=L(d),d=null,e=0),g=0;else break;return c}return a};var Ea=new V(null,"meta","meta",1499536964),xe=new V(null,"frame","frame",-1711082588),Fa=new V(null,"dup","dup",556298533),ye=new V(null,"simpleFullscreen","simpleFullscreen",-1591383385),ze=new V(null,"disableAutoHideCursor","disableAutoHideCursor",2039072105),Ae=new V(null,"backgroundThrottling","backgroundThrottling",272836265),Be=new V(null,"minWidth","minWidth",-204293526),Ce=new V(null,"sync-with-disk","sync-with-disk",-736184661),se=new V(null,"val","val",128701612),pe=new V(null,"fallback-impl",
"fallback-impl",-1501286995),Ca=new V(null,"flush-on-newline","flush-on-newline",-151457939),De=new V(null,"webPreferences","webPreferences",-1267169265),Da=new V(null,"readably","readably",1129599760),he=new V(null,"more-marker","more-marker",-14717935),Ee=new V(null,"fullscreen","fullscreen",-4371054),Ga=new V(null,"print-length","print-length",1931866356),Fe=new V(null,"alwaysOnTop","alwaysOnTop",-796802727),oe=new V(null,"alt-impl","alt-impl",670969595),Ge=new V(null,"minHeight","minHeight",-1635998980),
He=new V(null,"show","show",-576705889);var ea={Sb:{}};ea.Sb.bc="production";("function"==m(null)||t(Oa,null))&&Wc(null,ed());function Ie(){var a=Je.readFileSync([w.c(Ke),"/shortcut.conf"].join(""),"utf8");a="/(?:)/"===""+w.c("\n")?fc.f(vd(S("",X.f(w,F(a)))),""):vd((""+w.c(a)).split("\n"));if(1<Q(a))a:for(;;)if(""===(null==a?null:bb(a)))a=null==a?null:cb(a);else break a;return a}function Le(a){return/^[\s\xa0]*$/.test(null==a?"":String(a))};"undefined"!==typeof require&&require("zlib");va=function(){function a(a){var c=null;if(0<arguments.length){c=0;for(var e=Array(arguments.length-0);c<e.length;)e[c]=arguments[c+0],++c;c=new H(e,0,null)}return b.call(this,c)}function b(a){return console.log.apply(console,Ma(a))}a.I=0;a.H=function(a){a=F(a);return b(a)};a.B=b;return a}();
wa=function(){function a(a){var c=null;if(0<arguments.length){c=0;for(var e=Array(arguments.length-0);c<e.length;)e[c]=arguments[c+0],++c;c=new H(e,0,null)}return b.call(this,c)}function b(a){return console.error.apply(console,Ma(a))}a.I=0;a.H=function(a){a=F(a);return b(a)};a.B=b;return a}();var Me=["file://",w.c(__dirname),"/../app.html"].join(""),Ne=require("electron"),Oe=Ne.ipcMain,Pe=Ne.app,Qe=Ne.clipboard,Re=Ne.BrowserWindow,Se=Ne.globalShortcut,Te=Ne.Menu,Ue=Pe.dock;require("path");
var Je=require("fs-extra");"undefined"!==typeof Ue&&Ue.hide();var Ke=[w.c(Pe.getPath("home")),"/.finda"].join(""),Ve=[w.c(Ke),"/.license"].join("");Je.copySync([w.c(__dirname),"/../../integrations"].join(""),[w.c(Ke),"/integrations"].join(""));var We=[w.c(Ke),"/shortcut.conf"].join("");q(Je.existsSync(We))||Je.writeFileSync(We,"# Finda global shortcut, formatted as an Electron accelerator: https://github.com/electron/electron/blob/master/docs/api/accelerator.md\n# For example:\n#\n# Ctrl+Space\n# Command+Space\n# Ctrl+Shift+3\n#\n# Note that all modifiers must be listed.\n# So this last shortcut must be Ctrl+Shift+3 rather than Ctrl+# (assuming your keyboard has the # on the 3 key).\n#\n# If you want to use Command+Space as the shortcut, you must first remove Spotlight's usage of that shortcut via the OS X System Preferences.\n#\n# Finda must be restarted for changes to take effect.\n\nCtrl+\\");
q(Je.existsSync([w.c(Ke),"/.ignore"].join("")))||Je.writeFileSync([w.c(Ke),"/.ignore"].join(""),".license\ncaches/");var Xe;try{var Ye=X.f(function(a){return a.trim()},Ie());Xe=J(fd(ad(Le),fd(ad(function(a){return a.startsWith("#")}),Ye)))}catch(a){Xe="Ctrl+\\"}var Ze={shortcut:Xe},$e=require("crypto");function af(a){return $e.createHash("sha256").update(a,"utf8").digest("hex")}
function bf(a){var b=a.email;if(q(b)){var c=a["purchase-date"];if(q(c))return a=a.key,q(a)?N.f(a,af(["salt",w.c(b),w.c(c)].join("")).substring(0,8)):null}return null}function cf(){try{var a=JSON.parse(Qe.readText());if(!q(bf(a)))throw Error("Assert failed: (valid-license? l)");return a}catch(b){return null}}var df=new Ba(null,7,"17;High Sierra;16;Sierra;15;El Capitan;14;Yosemite;13;Mavericks;12;Mountain Lion;11;Lion".split(";"),null),ef=vc(J(require("os").release().split(".")),df),ff;
try{var gf=JSON.parse(Je.readFileSync(Ve)),hf=bf(gf);if(!q(q(hf)?hf:"number"===typeof gf.opens))throw Error('Assert failed: (or (valid-license? l) (number? (aget l "opens")))');ff=gf}catch(a){ff={opens:0,note:"If you can't afford to purchase Finda, please email me: kevin@keminglabs.com. I'd be happy to give you a license until you get to a financially better spot. --Kevin"}}var jf=new bd(ff,null,null,null);
(function kf(a,b,c){if(null!=a&&null!=a.wb)return a.wb(0,b,c);var e=kf[m(null==a?null:a)];if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);e=kf._;if(null!=e)return e.j?e.j(a,b,c):e(a,b,c);throw u("IWatchable.-add-watch",a);})(jf,Ce,function(a,b,c,d){return Je.writeFileSync(Ve,JSON.stringify(d))});dd.f(jf,Ac);function lf(){var a=cf();q(a)?cd(jf,a):dd.f(jf,function(){return function(a){a.opens+=1;return a}}(a))}
function mf(){var a=eb(jf);return ef?{status:"old-build"}:q(bf(a))?{status:"active"}:300>a.opens?{status:"trial-active"}:{status:"trial-expired"}}function nf(a){a.datatronIsVisible=!1;a.send("hide");return Te.sendActionToFirstResponder("hide:")}function of(a){lf();a.datatronIsVisible=!0;a.send("show",mf(),Ze);a.show();return a.focus()}Oe.on("show",function(a){a=Re.fromWebContents(a.sender);return q(a)?q(a.datatronIsVisible)?null:of(a):null});
Oe.on("hide",function(a){a=Re.fromWebContents(a.sender);return q(a)?q(a.datatronIsVisible)?nf(a):null:null});var pf;a:for(var qf=[xe,ye,ze,Be,De,Ee,Fe,Ge,He],rf=[!1,!0,!0,800,new Ba(null,1,[Ae,!1],null),!0,!0,600,!1],sf=qf.length,tf=0,uf=ub(Jd);;)if(tf<sf){var vf=tf+1,wf=uf.za(null,qf[tf],rf[tf]);tf=vf;uf=wf}else{pf=wb(uf);break a}
Pe.on("ready",function(){var a=new Re(we(pf));a.setVisibleOnAllWorkspaces(!0);a.loadURL(Me);a.on("ready-to-show",function(a){return function(){return of(a)}}(a));try{Se.register(Ze.shortcut,function(a){return function(){return q(a.datatronIsVisible)?nf(a):of(a)}}(a))}catch(b){Je.removeSync(We),Pe.relaunch(),Pe.exit()}a.on("blur",function(a){return function(){return a.send("blur")}}(a));return a});