version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:4
    volumes:
      - './tmp/storage:/verdaccio/storage'
      - './verdaccio/conf:/verdaccio/conf'
  https-portal:
    environment:
      STAGE: local
      DOMAINS: 'example.com -> http://verdaccio:4873'
