version: '2'

services:
  verdaccio:
    build: ./verdaccio
    container_name: verdaccio-https
    ports:
      - '4873:4873'
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - verdaccio:verdaccio
    environment:
      DOMAINS: 'registry.tryorbit.com -> http://verdaccio:4873'
      CLIENT_MAX_BODY_SIZE: 50M
