plugins: /verdaccio/plugins
storage: /verdaccio/storage

max_body_size: 100mb

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd

uplinks:
  yarnjs:
    url: https://registry.yarnpkg.com/
    max_fails: 100
    cache: false
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100
    cache: false

middlewares:
  audit:
    enabled: true

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: trace }
