import { view } from '@mcro/black'
import * as React from 'react'
import * as UI from '@mcro/ui'
import { ItemResolverResolverProps } from '../ItemResolver'
import { PersonBit } from '@mcro/models'
import { last } from 'lodash'
