storage: /tmp/.verdaccio-storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  yarn:
    url: https://registry.yarnpkg.com
  npmjs:
    url: https://registry.npmjs.org

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: http }
