[package]
name = "screendiff"
version = "0.1.0"
authors = ["natew <natewienert@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "screendiff"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
x11-screenshot = "0.1.0"