#!/bin/bash

. $(dirname $0)/../../__common
cd $ROOT

IS_PROD=false
if [ "$NODE_ENV" = "production" ]; then
  IS_PROD=true
fi

echo "is prod? $IS_PROD"

startApiDev() {
  cd apps/api
  npm run dev
}

startApi() {
  cd apps/api
  npm start
}

if [ "$IS_PROD" = true ]; then
  startApi
else
  startApiDev
fi

fg
