#!/bin/bash

. $(dirname $0)/../../bin/__common

IS_PROD=false
if [ "$NODE_ENV" = "production" ]; then
  IS_PROD=true
fi

echo "is prod? $IS_PROD"

if [ "$IS_PROD" = true ]; then
  npm start
else
  npm run dev
fi
